---
layout: post
title: Daily Bits - May 2023
date: '2023-05-02 08:31'
tags: 
  - daily bits
categories: 
  - 2023
  - Daily Bits
---

20230517

- Spent the day reorganizing, renaming, and documenting the E5 coral RNA/sRNA-seq data.



20230516

- Spent _all day_ (seriously!) getting E5 coral RNA-seq data downloaded from Azenta via sFTP. SUPER ANNOYING!




20230515

- Read Ch.6 of "Invisible Women"

- Lab meeting

  - Discussed Ch.6 of "Invisible Women"

- Helped out Olivia [with her RStudio Server issue](https://github.com/RobertsLab/resources/issues/1651)

- Downloaded Hollie Putnam coral sRNA-seq data from Azenta project 30-852430235.

  - Download option is over sFTP, which constantly hangs. Requires constant monitoring and reconnecting/downloading. Very annoying.

- CEABIGR meeting

  - Not too much, as Steven and I discussed bisulfite SNP stuff on Friday at Science Hour. No Yaamini this week, so not much to talk about. Plus, Steven was at the hatchery.



20230512

- Continued tweaking containerization testing.

- Science Hour

  - Steven at the hatchery.





20230511

- Pub-a-thon

  - Discussed bisulfite SNP analysis in more detail. `EpiDiverse/snp` pipeline might not be identifying `C > T` SNPs like we want... Or, _is_ that what we want?? Turns out `EpiDiverse/snp` masks bisulfite conversions to allow for "normal" SNP analysis without the confounding factor of bisulfite conversions...

- Worked on containerization.



20230510

- Spent most of the day thinking/messing around with bisulfite SNP calls. Even [started a GitHub Discussion](https://github.com/RobertsLab/resources/discussions/1649).



20230509

- Ordered a bunch of stuff for Ariana.

- Messed around with understanding bisulfite SNP calls using `bcftools`.



20230508

- [Installed `ngsTools` on Raven.](https://github.com/RobertsLab/resources/issues/1645) (GitHub Issue)

- Lab Meeting

  - Chris discussed eDNA project for the summer course she's running.

- CEABIGR meeting:

  - Discussed/examined how to convert VCF to GLF (genome likelihood file).

- Submitted E5 _P.verrucosa_ Hisat2/StringTie/lncRNA script using older version of StringTie to avoid segmentation fault.



20230502

- Helped reset a hanging [Rstudio Server session which Celeste was having an issue with](https://github.com/course-fish546-2023/assistance-public/issues/6).

- Wrote up a few notebook entries.

- Finished [Pacific geoduck (_Panopea generosa_)](http://en.wikipedia.org/wiki/Geoduck) lncRNA identification.
