---
layout: post
title: RNA Isolation & Quantification - C.bairdi RNA from Samples 6212_132_9 6212_334_12 6212_485_26
date: '2020-02-11 15:20'
tags:
  - Tanner crab
  - RNA isolation
  - RNA quantification
  - Qubit3.0
  - Qubit hsRNA assay
categories:
  - Tanner Crab RNAseq
---
We are supposed to get RNA sent out for sequencing today, but it turns out that a few of the designated samples have insufficient RNA in them. So, I'm going to attempt to isolate enough RNA from the following samples in order to have enough RNA to send to Genewiz today:

- 6212_132_9

- 6212_334_12

- 6212_485_2

Isolated RNA using the [Quick DNA/RNA Microprep Kit](https://github.com/RobertsLab/resources/blob/master/protocols/Commercial_Protocols/ZymoResearch_quick-dna-rna_microprep_plus_kit_20190411.pdf) (ZymoResearch; PDF) according to the manufacturer's protocol for liquids/cells in RNAlater.

- Used 35uL from each RNAlater/hemocyte slurry.

- Mixed with equal volume of H<sub>2</sub>O (35uL).

- Retained DNA on the Zymo-Spin IC-XM columns for isolation after RNA isolation.

- Performed on-column DNase step.

- RNA was eluted in 15uL H<sub>2</sub>O

RNA was quantified on the Roberts Lab Qubit 3.0 using the RNA High Sensitivity Assay (Invitrogen), using 2uL of each sample.

RNA was stored in a temporary box in the [-80<sub>o</sup>C freezer](http://b.link/srlab-80C) with the rest of the samples intended to be sent for sequencing.

---

#### RESULTS

Qubit restuls (Google Sheet):

- [20200211_qubit_crab_RNA](https://docs.google.com/spreadsheets/d/1BzPNM_9smWWgCCxST1rUQeIkyDLjfXQ0drul76kVebY/edit?usp=sharing)

| Sample ID   | [RNA] (ng/uL) |
|-------------|---------------|
| 6212_485_26 | 5.46          |
| 6212_132_9  | 7.21          |
| 6212_334_12 | 8.38          |

Will pass these off to Grace to get prepped to send out for sequencing.
