---
layout: post
title: DNA Isolation and Quantification - C.bairdi gDNA from EtOH Preserved Tissue
date: '2020-01-08 15:09'
tags:
  - tanner crab
  - DNA isolation
  - EZNA Mollusc DNA Kit
  - Qubit3.0
  - Qubit BR dsDNA
  - Chionoecetes bairdi
categories:
  - Miscellaneous
---
I isolated gDNA from ethanol-preserved _C.bairdi_ muscle tissue from sample 20102558-2729 (SPNO-ReferenceNO). This sample was chosen as it had `0` in the `SMEAR_result` and `BCS_PCR_results` columns, indicating it should be free of _Hematodinium_. See the sample spreadsheet linked below for more info.

_C.bairdi_ ethanol-preserved sample sheet from Pam Jensen (GoogleSheets):

- [Sample info 4 Steven etal 112719](https://drive.google.com/file/d/0B2S_90rPaQMzTU5NenBFcG1kLVdxa1AyR2FDcjMzWHJZN1J3/view?usp=sharing)

I performed four separate isolations using 50mg of tissue. Samples were "ground" <sup>*</sup> in liquid nitrogen (LN2) with ceramic mortar/pestle and then processed using the E.Z.N.A. Mollusc DNA Kit according to the manufacturer's protocol, with the following notes/changes:

- Used ThermoFisher Proteinase K (18mg/mL) instead of that supplied by kit. Kit Proteinase K was moldy (!); the kit is nearly four years old...

- Lysed tissue for 1hr.

- Eluted with 200uL for each sample and pooled for final total volume of ~800uL.

Sample was quantified on the Robert Lab Qubit 3.0 using the DNA Broad Range assay, using 1uL of sample.


<sup>*</sup> _The tissue did not powder as one would expect when grinding in liquid nitrogen. Instead, despite all utensils being pre-chilled with LN2 and tissue being actively ground under LN2, the tissue became a frozen paste that adhered to the pestle. I've never experienced this before, but I also have not attempted to grind ethanol-preserved tissue in LN2 before._

---

#### RESULTS

Qubit data (Google Sheet):

- [20200108_qubit_crab_gDNA](https://docs.google.com/spreadsheets/d/1uEK8OYpvxVyI2iQGFXTm60wQDonN2kcCy0Kg70kU8-c/edit?usp=sharing)


Yield is very good: ~51ng/uL * 800uL = 40ug

Will run sample on gel and NanoDrop to evalute gDNA integrity/quality.

Sample was stored at -80<sup>o</sup>C in:

[Rack 6, 4, 1](http://b.link/srlab-80C) in [C.bairdi gDNA Box #1](https://docs.google.com/spreadsheets/d/1D09mPvwDReuUNR36p_BrlrNfev_Ko1F83W4EKdAO6bk/edit?usp=sharing)
