---
layout: post
title: Primer Design and In-Silico Testing - Geoduck Reproduction Primers
date: '2020-07-30 21:02'
tags:
  - geoduck
  - Panopea generosa
  - Primer3
  - EMBOSS
  - primersearch
  - jupyter
categories:
  - Miscellaneous
---
[Shelly asked that I re-run the primer design pipeline](https://github.com/RobertsLab/resources/issues/974) that Kaitlyn had previously run to design a set of reproduction-related qPCR primers. Unfortunately, Kaitlyn's Jupyter Notebook wasn't backed up and she accidentally deleted it, I believe, so there's no real record of how she designed the primers. However, I do know that she was unable to run the EMBOSS primersearch tool, which will check your primers against a set of sequences for any other matches. This is useful for confirming specificity.

In an attempt to replicate what Katilyn previously did, I used the following:

- [List of sequence IDs from _P.generosa_ genes FastA](https://github.com/RobertsLab/resources/issues/822#issuecomment-572313717) (GitHub Issue comment from Steven)

- [_P.generosa_ genes FastA](https://osf.io/ct623/) (OSF repo)

- [Abbreviated gene names used to name primers](https://docs.google.com/spreadsheets/d/1vkUQvqNUN-9ntv0NoVDAtD8zA-p9e3xosGwsWSFV0qk/edit#gid=0) (Google Sheet)


Primers were designed using [Primer3](https://sourceforge.net/projects/primer3/files/primer3/).

Primers were checked for specificity, allowing a 20 percent mismatch, using the [EMBOSS primersearch program](http://emboss.open-bio.org/rel/rel6/apps/primersearch.html).

This was all documented and run in a Jupyter Notebook (GitHub):

- [20200730_swoose_geoduck_repro_check.ipynb](https://github.com/RobertsLab/code/blob/master/notebooks/sam/20200730_swoose_geoduck_repro_check.ipynb)

---

#### RESULTS

Output folder:

- [20200730_pgen_primer_design](https://gannet.fish.washington.edu/Atumefaciens/20200730_pgen_primer_design/)

The number of matches identified in the _P.generosa_ genes FastA file for each primer set are in the table below. Note the following:

- Primer sets selected/tested were the first primer set generated by Primer3.

- There was a 20% mismatch allowed when checking specificity.

- Counts listed in table should be divided by 2 (this is explained in the [Jupyter Notebook]((https://github.com/RobertsLab/code/blob/master/notebooks/sam/20200730_swoose_geoduck_repro_check.ipynb))). Thus, an entry with a value of `2` only has a single match in the entire _P.generosa_ genes FastA file.

| SeqID                    | PrimerName | Matches |
|--------------------------|------------|---------|
| PGEN_.00g025890-vv0.74.a | TIF3s12    | 2       |
| PGEN_.00g070040-vv0.74.a | APLP       | 2       |
| PGEN_.00g188130-vv0.74.a | FEN1       | 2       |
| PGEN_.00g194630-vv0.74.a | ECHD3      | 2       |
| PGEN_.00g338640-vv0.74.a | NSF        | 2       |
| PGEN_.00g288180-vv0.74.a | TIF3s4a    | 4       |
| PGEN_.00g245080-vv0.74.a | TIF3s10    | 8       |
| PGEN_.00g132030-vv0.74.a | TIF3s8-1   | 10      |
| PGEN_.00g079690-vv0.74.a | TIF3s7     | 14      |
| PGEN_.00g088260-vv0.74.a | NFIP1      | 36      |
| PGEN_.00g224740-vv0.74.a | GLYG       | 46      |
| PGEN_.00g280110-vv0.74.a | SPTN1      | 496     |
| PGEN_.00g082590-vv0.74.a | TIF3s5     | 742     |
| PGEN_.00g287540-vv0.74.a | RPL5       | 2570    |
| PGEN_.00g132040-vv0.74.a | TIF3s8-2   | 7800    |
| PGEN_.00g114060-vv0.74.a | GSK3B      | 8596    |
| PGEN_.00g000750-vv0.74.a | TIF3s6b    | 15512   |
