---
layout: post
title: RNA Isolation and Quantification - Dorothy Mussel Gill Samples
date: '2022-07-26 15:35'
tags: 
  - RNA isolation
  - RNA quantification
  - Qubit
  - mussel
  - gill
categories: 
  - Miscellaneous
---
Isolated RNA from a subset of Dorothy's mussel gill samples:

- T01-G
- T02-G
- T03-G
- T04-G
- T05-G
- T06-G
- T07-G
- T08-G
- T09-G
- T10-G
- T16-G
- T17-G
- T18-G
- T19-G
- T20-G
- T21-G
- T22-G
- T23-G
- T24-G
- T25-G

### RNA Isolation

RNA was isolated using RNAzol RT and the Direct-zol RNA Microprep Kit (ZymoResearch), with the DNase I on-column treatment step. Small portions of frozen gill tissue were removed from tubes, placed in RNAzol RT and immediately homoegnized. Forceps were rinsed in distilled H<sub>2</sub>O, soaked in 10% bleach solution for 10mins, and then rinsed in distilled H<sub>2</sub>O before re-use. All centrifugation steps were performed at 16,000g for 1.5mins. Here's a brief overview of the process.

Tissues were homogenized in 500uL of RNAzol RT with "disposable" platic mortar/pestle tubes (1.5mL). After homogenization, an additional 500uL of RNAzol RT was added to the tube, vortexed and incubated at RT for 10mins. Insoluble debris was pelleted and supernatant was transferred to a 2.0mL tube. An equal volume (1mL) of 100% ethanol was added to this supernatant and mixed thoroughly by pipetting. Direct-zol Microprep Kit protocol was followed from here on, including on-column DNase I treatment. All samples were eluted with 15uL of H<sub>2</sub>O.

NOTE: T25-G utilized Direct-zol DNA/RNA Miniprep Kit (ZymoResearch), as there was insufficient columns in the microprep kit. RNA was eluted with 40uL H<sub>2</sub>O.

RNA was quantified using the Roberts Lab Qubit 3.0 using the Qubit RNA High Sensitivity assay.

### Reverse Transcription

RNA was reverse transcribed using 150ng of total RNA from each sample using M-MLV Reverse Transcriptase (Promega) and oligo dT primers (Promega). All reactions were performed in standard 0.5uL snapcap microfuge tubes. 

cDNA calculations (Google Sheet):

- [20220726-medu-cDNA_calcs](https://docs.google.com/spreadsheets/d/1S7980PcVi-6iNP9NlqShVxZra9koeA33JwIKp3PMEmY/edit?usp=sharing)

All RNA and cDNA was stored @ -80<sup>o</sup>C in [Dorothy's -80<sup>o</sup>C Box](https://docs.google.com/spreadsheets/d/1iTPlCXN4X03D1XWfe_A-1zIyD7dF1tKDYvUayIayQio/edit?usp=sharing).


---

#### RESULTS

Qubit results (Google Sheet):

- [20220726_qubit_medu_gill_RNA](https://docs.google.com/spreadsheets/d/1FXTDEZ_t38kdsN0_I2Pry2mtMotRAPKhEvtN-4mCG4c/edit?usp=sharing)


Primary experiment workbork (Google Sheets):

- [Mussel Experiment Data](https://docs.google.com/spreadsheets/d/13S5opQulcaCQM8ybhY3-RIO9g8fIxx6x7oXAiI_TVKg/edit?usp=sharing)
