---
layout: post
title: RNA Isolation and Quantification - C.bairdi RNA from Hemolymph Pellets in RNAlater
date: '2020-03-06 13:24'
tags:
  - RNA isolation
  - RNA quantification
  - Qubit
  - 1x hsRNA assay
  - Tanner crab
  - Chionoecetes bairdi
categories:
  - Tanner Crab RNAseq
---
Based on [qPCR results testing for residual gDNA from 20200225](https://robertslab.github.io/sams-notebook/2020/02/25/qPCR-C.bairdi-Primer-Tests-on-gDNA.html), a set of 24 samples were identified that required DNase treatment and/or additional RNA. I opted to just isolate more RNA from all samples, since the kit includes a DNase step and avoids diluting the existing RNA using the Turbo DNA-free Kit that we usully use. Isolated RNA using the [Quick DNA/RNA Microprep Kit](https://github.com/RobertsLab/resources/blob/master/protocols/Commercial_Protocols/ZymoResearch_quick-dna-rna_microprep_plus_kit_20190411.pdf) (ZymoResearch; PDF) according to the manufacturer's protocol for liquids/cells in RNAlater.

- Used 35uL from each RNAlater/hemocyte slurry.

- Mixed with equal volume of H<sub>2</sub>O (35uL).

- Retained DNA on the Zymo-Spin IC-XM columns for isolation after RNA isolation.

- Performed on-column DNase step.

- RNA was eluted in 15uL H<sub>2</sub>O

RNA was quantified on the Roberts Lab Qubit 3.0 using the RNA High Sensitivity Assay (Invitrogen), using 2uL of each sample.


---

#### RESULTS

Qubit results (Google Sheet):

- [20200306_qubit_crab_RNA](https://docs.google.com/spreadsheets/d/1ODXr7Yp67XcuAZjZSgbF45fUC-EFrH6FYeEs_RNwPiI/edit?usp=sharing)

Most samples have good yields. Only a few are a bit low. Will check all samples for residual gDNA.
