---
layout: post
title: RNA Quantification - C.gigas PolyIC Diploid MgCl2
date: '2023-08-16 06:35'
tags: 
  - polyIC
  - Crassostrea gigas
  - Pacific oyster
categories: 
  - Miscellaneous
---
Steven [asked me to generate cDNA](https://github.com/RobertsLab/resources/issues/1675) (GitHub Issue) from [_Crassostrea gigas_ (Pacific oyster)](http://en.wikipedia.org/wiki/Pacific_oyster) RNA, as part of Matt George's polyIC project. I had [previously quantified RNA from five diploid and five triploid samples](https://robertslab.github.io/sams-notebook/2023/07/21/RNA-Quantification-C.gigas-PolyIC.html) (Notebook), but the [qPCR results](https://robertslab.github.io/sams-notebook/2023/07/26/qPCR-C.gigas-polyIC.html) (Notebook) didn't reveal much. Plus, the diploids and triploids weren't the same treatment types (i.e. the diploids were poly:IC-injected, whereas the triploids were controls - so they weren't really comparable). So, Steven asked that I find comparable set of samples so that we'd have either diploid controls or triploids which were poly:IC-injected. Looking in [the freezer box for samples](https://docs.google.com/spreadsheets/d/1VKN9vogT6q5IpOo-PoB9WNeFUT3k_BCQ8_P7_DY81oM/edit#gid=0) (Google sheet), I found four diploid MgCl<sub>2</sub> control RNA samples. Before starting reverse transcription, I felt it would be best to quantify the RNA using the Qubit 3.0 using the Broad Range Assay. Steven and I discussed which samples to use earlier this week.

Used 1uL of each sample.

See Results section below for sample/tube labels.


---

#### RESULTS


- [20230816-qubit-cgig-polyIC-RNA](https://docs.google.com/spreadsheets/d/1AoHltNOTup5GoOJ2ef8mE5u_Q9ARAfetgTJ5d7M05Og/edit?usp=sharing) (Google Sheet)

All samples had ample amount of RNA. Will proceed with reverse transcription.

