---
layout: post
title: Summary - Geoduck RNAseq Data
date: '2021-07-12 07:29'
tags: 
  - NCBI
  - geoduck
  - Panopea generosa
  - RNAseq
categories: 
  - Project Summary
---
[Per this GitHub Issue](https://github.com/RobertsLab/resources/issues/1247), I've compiled a summary table, with links, of all of our [_Panopea generosa_ (Pacific geoduck)](http://en.wikipedia.org/wiki/Geoduck) RNAseq data as it exists in NCBI. This will be a "dynamic" notebook entry, whereby I will update this post continually as we acquire new data and/or change the information we'd like to have here.


| Run                                                                       | BioSample                                                           | Experiment                                                | Library_ID           | Sample_Name               | Tissue/Treatment                     | Sequencer    |
|---------------------------------------------------------------------------|---------------------------------------------------------------------|-----------------------------------------------------------|----------------------|---------------------------|--------------------------------------|--------------|
| [SRR12218868](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR12218868) | [SAMN15524261](https://www.ncbi.nlm.nih.gov/biosample/SAMN15524261) | [SRX8729323](https://www.ncbi.nlm.nih.gov/sra/SRX8729323) | Geoduck-heart-RNA    | geoduck-20150811-heart    | heart                                | HiSeq 4000   |
| [SRR12218869](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR12218869) | [SAMN15524260](https://www.ncbi.nlm.nih.gov/biosample/SAMN15524260) | [SRX8729322](https://www.ncbi.nlm.nih.gov/sra/SRX8729322) | Geoduck-gonad-RNA    | geoduck-20150811-gonad    | gonad                                | HiSeq 4000   |
| [SRR12218870](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR12218870) | [SAMN15524251](https://www.ncbi.nlm.nih.gov/biosample/SAMN15524251) | [SRX8729321](https://www.ncbi.nlm.nih.gov/sra/SRX8729321) | Geoduck-ctenidia-RNA | geoduck-20150811-ctenidia | ctenidia                             | HiSeq 4000   |
| [SRR12226692](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR12226692) | [SAMN15524260](https://www.ncbi.nlm.nih.gov/biosample/SAMN15524260) | [SRX8735427](https://www.ncbi.nlm.nih.gov/sra/SRX8735427) | NR006                | geoduck-20150811-gonad    | gonad                                | NovaSeq 6000 |
| [SRR12226693](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR12226693) | [SAMN15524251](https://www.ncbi.nlm.nih.gov/biosample/SAMN15524251) | [SRX8735426](https://www.ncbi.nlm.nih.gov/sra/SRX8735426) | NR012                | geoduck-20150811-ctenidia | ctenidia                             | NovaSeq 6000 |
| [SRR12207404](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR12207404) | [SAMN15517239](https://www.ncbi.nlm.nih.gov/biosample/SAMN15517239) | [SRX8718216](https://www.ncbi.nlm.nih.gov/sra/SRX8718216) | EPI_124              | EPI_124                   | juvenile(ambient)                    | HiSeq 4000   |
| [SRR12207405](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR12207405) | [SAMN15517238](https://www.ncbi.nlm.nih.gov/biosample/SAMN15517238) | [SRX8718215](https://www.ncbi.nlm.nih.gov/sra/SRX8718215) | EPI_123              | EPI_123                   | juvenile(ambient)                    | HiSeq 4000   |
| [SRR12207406](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR12207406) | [SAMN15517237](https://www.ncbi.nlm.nih.gov/biosample/SAMN15517237) | [SRX8718214](https://www.ncbi.nlm.nih.gov/sra/SRX8718214) | EPI_116              | EPI_116                   | juvenile(super-low)                  | HiSeq 4000   |
| [SRR12207407](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR12207407) | [SAMN15517236](https://www.ncbi.nlm.nih.gov/biosample/SAMN15517236) | [SRX8718213](https://www.ncbi.nlm.nih.gov/sra/SRX8718213) | EPI_115              | EPI_115                   | juvenile(super-low)                  | HiSeq 4000   |
| [SRR12227930](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR12227930) | [SAMN15517239](https://www.ncbi.nlm.nih.gov/biosample/SAMN15517239) | [SRX8736520](https://www.ncbi.nlm.nih.gov/sra/SRX8736520) | NR019                | EPI_124                   | juvenile(ambient)                    | NovaSeq 6000 |
| [SRR12227931](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR12227931) | [SAMN15517237](https://www.ncbi.nlm.nih.gov/biosample/SAMN15517237) | [SRX8736519](https://www.ncbi.nlm.nih.gov/sra/SRX8736519) | NR005                | EPI_116                   | juvenile(super-low)                  | NovaSeq 6000 |
| [SRR12212519](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR12212519) | [SAMN11259647](https://www.ncbi.nlm.nih.gov/biosample/SAMN11259647) | [SRX8723123](https://www.ncbi.nlm.nih.gov/sra/SRX8723123) | EPI_99               | EPI_99                    | 10k day 5, post-fertilization larvae | HiSeq 4000   |
| [SRR12227929](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR12227929) | [SAMN11259647](https://www.ncbi.nlm.nih.gov/biosample/SAMN11259647) | [SRX8736518](https://www.ncbi.nlm.nih.gov/sra/SRX8736518) | NR021                | EPI_99                    | 10k day 5, post-fertilization larvae | NovaSeq 6000 |
| [SRR8788211](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR8788211)   | [SAMN11259647](https://www.ncbi.nlm.nih.gov/biosample/SAMN11259647) | [SRX5578033](https://www.ncbi.nlm.nih.gov/sra/SRX5578033) | NR021                | EPI_99                    | 10k day 5, post-fertilization larvae | NovaSeq 6000 |