project:
  type: website
  output-dir: docs


website:
  title: "robertslab.info"
  navbar:
    background: primary
    search: true
    # left:
    #   - text: "What"
    #     file: index.qmd
    #   - text: "Who"  
    #     file: publications.qmd
    #   - text: "How"  
    #     file: posts.qmd
    #  
    right:
      - icon: hdd-network
        menu:
          - text: raven
            url:  http://raven.fish.washington.edu:8787
          - text: gannet
            url:  https://gannet.fish.washington.edu
    
      - icon: journal-code
        menu:
          - text: sam
            url:  https://robertslab.github.io/sams-notebook/
          - text: steven
            url:  https://sr320.github.io
      - icon: github
        menu:
          - text: Lab Organization
            url:  https://github.com/RobertsLab
          - text: Edit Roberts Lab website
            url: https://github.com/RobertsLab/lab-website
      - icon: calendar-week
        href: https://calendar.google.com/calendar/embed?src=mrc305@gmail.com&ctz=America/Vancouver
       


    
format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual



