---
layout: post
title: DNA Quantification - Re-quant Ronits C.gigas Diploid-Triploid Ctenidia gDNA Submitted to ZymoResearch
date: '2020-09-01 07:41'
tags:
  - Crassostrea gigas
  - ctenidia
  - diploid
  - triploid
  - ploidy
  - Pacific oyster
  - Qubit
  - dsDNA BR Assay
categories:
  - Miscellaneous
---
I received notice from ZymoResearch yesterday afternoon that the [DNA we sent on 20200820 for this project (Quote 3534)](https://robertslab.github.io/sams-notebook/2020/08/20/Samples-Submitted-Ronits-C.gigas-Diploid-and-Triploid-Ctenidia-to-ZymoResearch-for-WGBS.html) had insufficient DNA for sequencing for most of the samples. This was, honestly, shocking. I had even submitted well over the minimum amount of DNA required (submitted 1.75ug - only needed 1ug). So, I'm not entirely sure what happened here.

I went ahead and re-quantified these samples with the intent of sending them more DNA. Samples were fully thawed, mixed thoroughly by finger flicking, spun down, and quantified using the Roberts Lab Qubit 3.0 and the dsDNA BR Assay (Invitrogen). Used 2uL of each sample.

---

#### RESULTS

Qubit results (Google Sheet):

- [20200901_qubit_DNA_gigas_ronit_ploidy](https://docs.google.com/spreadsheets/d/1bhqnSDA1o8xa0Fg4iMcL-uxs9g2hc6_tRhKY7zZNt-Y/edit?usp=sharing)

Comparison table below shows the initial sample quantification (which can be found in the [Ronit's Samples Google Sheet](https://docs.google.com/spreadsheets/d/12c79wmH6pUida7fg_e_Y1QS6bc2Ve_cyb-KL41jMfxY/edit?usp=sharing)), as well as the concentrations determiend by Zymo, and today's quantification. The table also lists the volume needed to send an additional 1ug of DNA from each sample, based on today's quantifications.


| Sample_ID | [initial](ng/uL) | [Zymo](ng/uL) | [20200901](ng/uL) | Vol_for_1ug(uL) |
|-----------|------------------|---------------|-------------------|-----------------|
| D11-C     | 181              | 85.20         | 269               | 3.72            |
| D12-C     | 192              | 46.16         | 289               | 3.46            |
| D13-C     | 288              | 606.23        | 332               | 3.01            |
| D19-C     | 63.6             | 11.14         | 51.3              | 19.49           |
| D20-C     | 123              | 9.40          | 77                | 12.99           |
| T11-C     | 130              | 41.52         | 88                | 11.36           |
| T12-C     | 262              | 9.96          | 139               | 7.19            |
| T13-C     | 250              | 130.14        | 148               | 6.76            |
| T19-C     | 173              | 35.58         | 92.9              | 10.76           |
| T20-C     | 109              | 132.10        | 78.4              | 12.76           |


I'm not going to think too hard about what's going on here, but I am surprised at the concentration differences between all three measurements. It should also be noted that I believe the ZymoResearch concentrations provided were from the Agilent TapeStation, not a Qubit. The TapeStation is less accurate/sensitive than a dye-based quantification methodology like the Qubit.

Will send off 1ug of each sample, based on today's quants...
