---
date: 2018-01-16 22:07:11+00:00
layout: post
slug: samples-submitted-c-virginica-gdna-mbd-and-mspi-to-qiagen
title: Samples Submitted - C. virginica gDNA, MBD, and MspI to Qiagen
categories:
  - 2018
  - Samples Submitted
tags:
  - Crassostrea virginica
  - Eastern oyster
  - gDNA
  - MBD
  - MspI
  - Qiagen
---

Sent _Crassostrea virginica_ samples to Qiagen, as part of the collaboration we have with them for testing their new bisulfite conversion kit on various reduced representation DNA.

Samples were sent on dry ice via FedEx International Priority: [771231112481](https://www.fedex.com/apps/fedextrack/?action=track&tracknumbers=771231112481&clienttype=ivother)

Here are the samples I sent:

gDNA C.virginica - Genomic DNA, 20uL, 58.4ng/uL
MBD 1 virginica - Fragmented (~400bp average size), MBD-enriched, 25uL, 18.3ng/uL
MBD 2 virginica - Fragmented (~400bp average size), MBD-enriched, 25uL, 19.6ng/uL
MspI 1  virginica - gDNA digested with MspI, 25uL, 53.4ng/uL
MspI 2 virginica - gDNA digested with MspI, 25uL, 31.0ng/uL

Genomic DNA was isolated from mantle tissue using the E.Z.N.A. Mollusc DNA Kit (Omega). DNA was eluted with the Elution Buffer supplied with the kit.

MBD enrichment was performed using the MethylMiner Methylated DNA Enrichment Kit (Invitrogen). DNA was resuspended in Buffer EB (Qiagen).

MspI digestions were performed using MspI (NEB) and were subjected to a phenol:chloroform cleanup, post-digestion. DNA was resuspended in Buffer EB (Qiagen).

No tests have been performed on the samples to evaluate the presence/absence of non-oyster DNA.

Reference genome is available here: [https://www.ncbi.nlm.nih.gov/assembly/GCF_002022765.2/](https://www.ncbi.nlm.nih.gov/assembly/GCF_002022765.2/)

Notebook entries:



##### gDNA Isolation:






##### MBD:






##### MspI Digestion:



