---
layout: post
title: RNA Isolation - O.nerka Berdahl Brain Tissues
date: '2022-04-11 15:27'
tags: 
  - brain
  - sockeye salmon
  - RNA isolation
  - RNA quantification
  - qubit
  - Oncorhynchus nerka
categories: 
  - Miscellaneous
---
[Steven asked that I isolate RNA from the remainder of the Berdahl brain tissue samples](https://github.com/RobertsLab/resources/issues/1410) (GitHub issue).

For reference, [here's the original info provided regarding these samples](https://github.com/RobertsLab/resources/issues/1307) (GitHub issue).

Sample labelling was as follows:

Numbers refer to individuals:

1-15 are territorial individuals

16-30 are social individuals

Letters refer to tissues:

(A) brain
(B) liver
(C) gonads

The following brain samples were selected for RNA isolation:

- 6A
- 7A
- 8A
- 9A
- 10A
- 11A
- 12A
- 13A
- 14A
- 15A
- 17A
- 18A
- 19A
- 21A
- 22A
- 24A
- 26A
- 27A
- 28A
- 29A
- 30A


RNA was isolated using RNAzol RT (Molecular Research Center) and the Direct-zol RNA Microprep Kit (ZymoResearch), with the DNase I on-column treatment step. The brain tissues were split into 4 equal size portions. Each portion was homogenized individually. Forceps were rinsed in distilled H2O, soaked in 10% bleach solution for 10mins, and then rinsed in distilled H2O before re-use. All centrifugation steps were performed at 16,000g for 1 min. Here’s a brief overview of the process.

Tubes containing tissues were allowed to thaw completely at room temperature (RT). Tissues were homogenized in 500uL of TriReagent with “disposable” platic mortar/pestle tubes (1.5mL). After homogenization, an additional 500uL of TriReagent was added to the tube, vortexed and incubated at RT for 15mins. Homogenized samples were stored over night at -20<sup>o</sup>. 

The four tubes from each sample was pelleted and supernatant was transferred to a 15.0mL tube. An equal volume (4mL) of 100% ethanol was added to this supernatant and mixed thoroughly by vortexing. Direct-zol Microprep Kit protocol was followed from here on, including on-column DNase I treatment. Samples were eluted with 15uL of H2O.

RNA was quantified using the Roberts Lab Qubit 3.0 using the Qubit RNA High Sensitivity assay.

All RNA was stored @ -80<sup>o</sup>C in [Sam’s RNA Box #3](https://docs.google.com/spreadsheets/d/1j9jm3b91IkVfG0EsSjQpR--t2R97YXEQPaOFqsOqjhc/edit?usp=sharing).

---

#### RESULTS

Raw Qubit data (Google Sheet):

- [20220411-qubit-rna-oner](https://docs.google.com/spreadsheets/d/1WCslfKqWHNmQo5T54mIfD9T6ZCAjC2vEaHUe810OPKI/edit?usp=sharing)

SUMMARY TABLE:

| Sample | Concentration (ng/uL) | Elution Volume (uL) | Yield (ng) |
|--------|-----------------------|---------------------|------------|
| 6A     | 116                   | 15                  | 1740       |
| 7A     | 132                   | 15                  | 1980       |
| 8A     | 120                   | 15                  | 1800       |
| 9A     | 130                   | 15                  | 1950       |
| 10A    | 94                    | 15                  | 1410       |
| 11A    | 114                   | 15                  | 1710       |
| 12A    | 80                    | 15                  | 1200       |
| 13A    | 80.8                  | 15                  | 1212       |
| 14A    | 74.6                  | 15                  | 1119       |
| 15A    | 108                   | 15                  | 1620       |
| 17A    | 138                   | 15                  | 2070       |
| 18A    | 89                    | 15                  | 1335       |
| 19A    | 67.6                  | 15                  | 1014       |
| 21A    | 61.6                  | 15                  | 924        |
| 22A    | 108                   | 15                  | 1620       |
| 24A    | 83.8                  | 15                  | 1257       |
| 26A    | 98.8                  | 15                  | 1482       |
| 27A    | 110                   | 15                  | 1650       |
| 28A    | 118                   | 15                  | 1770       |
| 29A    | 124                   | 15                  | 1860       |
| 30A    | 102                   | 15                  | 1530       |