---
layout: post
title: RNA Isolation - O.nerka Berdahl Brain Tissues
date: '2021-12-22 05:07'
tags: 
  - brain
  - sockeye salmon
  - Oncorhynchus nerka
  - RNA isolation
  - RNA quantification
  - Qubit 3.0
categories: 
  - Miscellaneous
---
The previous round of RNA isolation (on [20211220](https://robertslab.github.io/sams-notebook/2021/12/20/RNA-Isolation-O.nerka-Berdahl-Tissues.html)) had poor yields for the brain tissue. As such, I needed to attempt to obtain RNA from some additional brain tissues.

For reference:

Sample labelling was as follows:

Numbers refer to individuals:

1-15 are territorial individuals

16-30 are social individuals

Letters refer to tissues:

(A) brain
(B) liver
(C) gonads

The following brain samples were selected for RNA isolation:

- 5A

- 20A

RNA was isolated using TriReagent and the Direct-zol RNA Microprep Kit (ZymoResearch), with the DNase I on-column treatment step. The brain tissues were split into 4 equal size portions. Each portion was homogenized individually. Forceps were rinsed in distilled H2O, soaked in 10% bleach solution for 10mins, and then rinsed in distilled H2O before re-use. All centrifugation steps were performed at 16,000g for 1 min. Here’s a brief overview of the process.

Tubes containing tissues were allowed to thaw completely at room temperature (RT). Tissues were homogenized in 500uL of TriReagent with “disposable” platic mortar/pestle tubes (1.5mL). After homogenization, an additional 500uL of TriReagent was added to the tube, vortexed and incubated at RT for 15mins. Insoluble debris was pelleted and supernatant was transferred to a 2.0mL tube. An equal volume (1mL) of 100% ethanol was added to this supernatant and mixed thoroughly by pipetting. The four portions from each sample was processed in a _single_ column (i.e. all four portions were combined and then processed with a single column - so, there were a total of two columns; one for each brain sample listed above) Direct-zol Microprep Kit protocol was followed from here on, including on-column DNase I treatment. Samples were eluted with 50uL of H2O.

RNA was quantified using the Roberts Lab Qubit 3.0 using the Qubit RNA High Sensitivity assay.

All RNA was stored @ -80oC in Sam’s RNA Box #2, slots A1 - B3

---

#### RESULTS

Raw Qubit data (Google Sheet):

- [20211222_qubit_oner](https://docs.google.com/spreadsheets/d/13Ki-2C7An2tI2bbQbOZsBWvijQhjNzJwoqk769HF8Fk/edit?usp=sharing)

SUMMARY TABLE:

| Sample | Concentration(ng/uL) | Volume(uL) | Yield(ng) | Tissue |
|--------|----------------------|------------|-----------|--------|
| 5A     | 1.23                 | 50         | 61.5      | brain  |
| 20A    | 30.6                 | 50         | 1530      | brain  |

The yield from 20A is good and should satisfy the goal of having RNA from two individuals within the "social" group. The yield from 5A is still low, but is potentially usable for RNAseq. I probably need to run an additional set of extractions from two more "territorial" brains in order to increase our flexibility in selecting individuals for sequencing, as well as have a better chance of having leftover RNA for other uses.