---
layout: post
title: DNA Isolation & Quantification - Additional C.bairdi gDNA from Sample 6129_403_26
date: '2020-02-10 14:12'
tags:
  - gDNA
  - DNA isolation
  - DNA quantification
  - tanner crab
  - Qubit 3.0
  - dsDNA BR assay
  - Chionoecetes bairdi
categories:
  - 2020
  - Miscellaneous
---
[Earlier today I isolated gDNA from C.bairi 6129_403_26 hemolymph pellets](https://robertslab.github.io/sams-notebook/posts/2020/2020-02-10-DNA-Isolation,-Quantification,-and-Gel-C.bairdi-gDNA-Sample-6129_403_26.html) and recovered decently intact gDNA that could be used for sequencing. However, I still need more gDNA, so will isolate that (and co-isolate RNA, since I'm going through the procedure anyway) using the rest of the sample using the Quick DNA/RNA Microprep Plus Kit (ZymoResearch)./

Followed the manufacturer's protocol with the following notes/changes:

- Used 480uL of sample, combined with 1:1 H<sub>2</sub>O (480uL), with 4:1 Lysis Buffer (3840uL) and mixed in 15mL conical

- Flow-through was retained in a 15mL concial for RNA isolation

- Eluted with 45uL

I combined this isolation with the [isolation from earlier today](https://robertslab.github.io/sams-notebook/posts/2020/2020-02-10-DNA-Isolation,-Quantification,-and-Gel-C.bairdi-gDNA-Sample-6129_403_26.html). I have updated that post to reflect this./

Quantified on the Roberts Lab Qubit 3.0 using the dsDNA BR Assay (Invitrogen) and 2uL of sample.


---

#### RESULTS

Qubit results (Google Sheet):

- [20200210_qubit_crab_gDNA-02](https://docs.google.com/spreadsheets/d/1aXLykULO63w-Y7diGGv_cSndkIu7uHWTBkhGpPQMGnU/edit?usp=sharing)

[DNA] = 40.7ng/uL in ~70uL

Yield = ~2849ng

Sample was stored at -80<sup>o</sup>C in:

[Rack 15, 4, 5](http://b.link/srlab-80C) in [C.bairdi gDNA Box #2](https://docs.google.com/spreadsheets/d/1EnI5UlvN8qoT3pB0VcP6Eu44BdiyyElToYA9VwukPEE/edit?usp=sharing)

This is still too low for PacBio sequencing. The UW facility suggests 5-8ug for 50X coverage of a 2Gbp genome (which is a rough guesstimate of the Tanner crab genome size) for a decent genome assembly. Maybe I can just send them 2000ng and see what we get out of it? Or, maybe I'll just isolate DNA from some other individuals and pool them. Will discuss with Steven and see how he feels about this.
