---
layout: post
title: Daily Bits - November 2022
date: '2022-11-01 10:03'
tags: 
  - daily bits
categories: 
  - Daily Bits
---


20221121

- Lab meeting

- Short day due to early out for Audrey's school.

---

20221118

- Short day due to early out for Audrey's school.

- Meeting with Linda Rhodes

  - Re-ran Jupyter Notebook using her original Silva files, but set to 99% clustering.

  - Reviewed using Conda environments.


---

20221117

- Pub-a-thon

- Dealt with some power outages in the morning.

---

2022116

- Went in to lab.

  - Showed Arianna around, got her keys, etc.

  - Updated/restarted Raven.

  - Worked on generating gene methylation coefficients of variation.

    - Struggled with converting data frame to matrix (required for `rowcvs()`).

    - RStudio Server locked up for a significant period of time.

---

20221115

- Worked heavily on CEABIGR CoV gene methylation.

- Worked heavily on CEABIGR diffs in max transcripts and mean gene methylation.

---

20221114

- Lab Meeting.

  - Discussed Ch.7 of The Disordered Cosmos

- C.virginica gene expression/DNA methylation meeting.

---

20221110

- Sort of giving up on the Circos exploration - plots of the data we have don't really fit into the Circos mode of data analysis (Circos is generally set up to examine spatial relationships of genome features).

- Started trying to make dot plots of the differences between the maximum number of transcripts per gene.

20221108

- Messed around a tiny bit with gettting max transcript count differences formatted for Circos.

---

20221107

- Lab meeting.

- C.virginica oyster gene expression meeting (i.e. CEABIGR)

---

20221104

- Meeting with Linda Rhodes to discuss 16s results

- Science Hour

- Oyster meeting with Lotterhos group to dicuss CEABIGR data.

- Power outage for a couple of hours...

---


20221103

- Worked a bit on looking at Laura's _M.magister_ [MBD-BSseq FastQC data](https://github.com/laurahspencer/DuMOAR/issues/15) (GitHub Issue).

- Pub-a-thon.

- Worked a bit on looking into Linda Rhodes 16s pipeline to see if we can figure out how to speed up the `vsearch` step. Nothing definitive found yet.

---

20221102

- Finished updating the Ballgown Rmd script for CEABIGR repo.

  - Updated corresponding REAMDE(s) with file descriptions for output(s) from Rmd.

- Possibly fixed `owl/nightingales` Synology Glacier backup. Existing Glacier backup was consistently failing immediately with unhelpful log message.

  - Created new backup task.

    - US West (Oregon).

    - New key/private key for Amazon AWS Glacier vault.

    - Task is running and has backed up ~265GB so far (out of 13.03TB). Will monitor progress over the next couple of weeks/months.

- Worked on CEABIGR manuscript.


---

20221101

- Worked on CEABIGR manuscript

- Transferred and updated Ballgown Rmd script to CEABIGR repo.