---
layout: post
title: DNA Isolation - C.bairdi 20102558-2729 EtOH-preserved Tissue via Three Variations Using Quick DNA-RNA MicroPrep Kit
date: '2020-01-22 13:38'
tags:
  - Tanner crab
  - 20102558-2729
  - DNA isolation
  - Quick DNA/RNA Microprep Kit
  - Qubit 3.0
  - 1x hsDNA Assay
  - Chionoecetes bairdi
categories:
  - Miscellaneous
---
[Previously, I isolated gDNA from a _C.bairdi_ EtOH-preserved muscle sample (20102558-2729) on 20200108](https://robertslab.github.io/sams-notebook/2020/01/08/DNA-Isolation-and-Quantification-C.bairdi-gDNA-from-EtOH-Preserved-Tissue.html) using the E.Z.N.A. Mollusc DNA Kit (Omega). Although the yields were excellent, the [DNA looked completely degraded on a gel](https://robertslab.github.io/sams-notebook/2020/01/09/DNA-Quality-Assessment-Agarose-Gel-and-NanoDrop-on-C.bairdi-gDNA.html) and running that DNA on a minION flowcell yielded relatively short reads (which wasn't terribly surprising).

So, to test out whether or not the degradation was due to the inherent age/preservation method of the sample, I decided to try another kit for gDNA isolation: Quick DNA/RNA MicroPrep Kit (ZymoResearch). I also decided to try three variations of the isolation protocol with very small pieces of tissue (~5 - 10mg):

- "damp": where the ethanol has _not_ been allowed to dry and homogenized with disposable mortar/pestle 1.5mL tube in 800uL of 1x DNA/RNA Shield.

- "dry": where the sample is allowed to dry (per the "FFPE Tissue" guidelines) and homogenized with disposable mortar/pestle 1.5mL tube in 800uL of 1x DNA/RNA Shield.

- minced: where the damp sample was minced with a razor blade and incubate in 300uL of 1x DNA/RNA Shield with 30uL PK Digestion Buffer and 15uL of Proteinase K solution at 55<sup>o</sup>C for 5hrs.

The remainder of the manufacturer's protocol was followed.

Samples were eluted in 30uL of H<sub>2</sub>O.

Samples were quantified on the Roberts Lab Qubit 3.0 using 1uL of each sample with the 1x dsDNA High Sensitivity Assay.

---

#### RESULTS

Qubit data (Google Sheet):

- [20200122_qubit_cbai_quick-DNA](https://docs.google.com/spreadsheets/d/1YXFRzvqTXIQ8cvZ77sRdlwllQad1s8UIUlmispuPZ6A/edit?usp=sharing)

Got DNA, decent yields (165ng, 138ng, and 510ng). Will proceed with checking quality on gel.

Samples were stored at -80<sup>o</sup>C in:

[Rack 6, 4, 1](http://b.link/srlab-80C) in [C.bairdi gDNA Box #1](https://docs.google.com/spreadsheets/d/1D09mPvwDReuUNR36p_BrlrNfev_Ko1F83W4EKdAO6bk/edit?usp=sharing)
