---
layout: post
title: RNA Isolation and Quantification - P.generosa Hemocytes from Shelly
date: '2020-11-19 08:33'
tags:
  - RNA isolation
  - quantificaiton
  - Qubit 3.0
  - Panopea generosa
  - geoduck
  - RNA
categories:
  - Miscellaneous
---
[Shelly asked me to isolate RNA from some _P.generosa_ hemocytes](https://github.com/RobertsLab/resources/issues/1022) (GitHub Issue) that she had.

RNA was isolated using the Quick DNA-RNA Microprep Plus Kit (ZymoResearch), according to the "Cells" protocol with the following notes/changes:

- All samples were lysed with 400uL of DNA/RNA Lysis buffer

- All samples were DNased using DNase aliquots from 20200127 (prepped by Kaitlyn Mitchell).

Samples were quantified using 1uL of sample with the Qubit RNA HS Assay (Invitrogen) on the Roberts Lab Qubit 3.0.

Two samples (022H and 044H) were too concentrated, so a 1:10 dilution was prepared and the two samples were re-quantified.

See the RESULTS section below for Qubit data and summary table of sample concentrations/yields.

---

#### RESULTS

All samples were stored in the [-80<sup>o</sup>C](https://docs.google.com/spreadsheets/d/1Qsvz3QTURlPF_hX05BQxjom3484WuMfqQ1ILl9LEljU/edit#gid=2006985773) in [Shellfish RNA Box #8, slots E7 - F3](https://docs.google.com/spreadsheets/d/1ax6C-muxUTXxFEtfWdswBvueLhmxZzmwZcO2ur-0q-Q/edit#gid=1794729843).

Qubit results:

- [20201119_qubit_pgen_hemo_RNA](https://docs.google.com/spreadsheets/d/1HFwpvskPTo8oliZJmz5ImBzOAIYuvh4OMLYpUM1sqfI/edit?usp=sharing) (Google Sheet)


| Sample | Concentration(ng/uL) | Elution_vol(uL) | Yield(ng) |
|--------|----------------------|-----------------|-----------|
| 021 H  | 176                  | 15              | 2640      |
| 022 H  | 382                  | 15              | 5730      |
| 041 H  | 102                  | 15              | 1530      |
| 044 H  | 580                  | 15              | 8700      |
| 14 H   | 194                  | 15              | 2910      |
| 15 H   | 124                  | 15              | 1860      |
