---
layout: post
title: MBD BSseq Library Prep - M.magister MBD-selected DNA Using Pico Methyl-Seq Kit
date: '2020-11-24 10:27'
tags:
  - Metacarcinus magister
  - dungeness crab
  - MBD
  - MBD-BSseq
  - bisfulite sequencing
categories:
  - Miscellaneous
---
[After finishing the final set of eight MBD selections on 20201103](https://robertslab.github.io/sams-notebook/2020/11/03/MBD-Selection-M.magister-Sheared-Gill-gDNA-16-of-24-Samples-Set-3-of-3.html), I'm finally ready to make the BSseq libraries using the [Pico Methyl-Seq Library Prep Kit (ZymoResearch)](https://github.com/RobertsLab/resources/blob/master/protocols/Commercial_Protocols/ZymoResearch_PicoMethylseq.pdf) (PDF). I followed the manufacturer's protocols with the following notes/changes (organized by each section in the protocol):

##### GENERAL

- Protocol was followed for using input DNA range 1ng - 50ng.

- All thermalcycling was performed on the Roberts Lab PTC-200 (MJ Research).

- All thermalcycling used a heated lid temp of 104<sup>o</sup>C, unless a different temp was specified in the protocol.

- All elution steps were performed with heated elution buffer (55<sup>o</sup>C).

- All index primers _not_ included with the kit were a mix of the Illumina TruSeq P5 primer (SRID: 1733) and an Illumina TruSeq P7 index primer (see table at bottom of page). The mix consisted of 10uM each of P5 and P7 primers. [See the Roberts Lab Primer Database](https://docs.google.com/spreadsheets/d/14m2kkFhxcoKWWIGoAD_7VOVsAg9wilME2UcSLqfnqLI/edit?usp=sharing) (Google Sheet) for info on the primers.

##### SECTION 2

- Used 0.5mL PCR tubes, since 0.2uL tubes were not specified and the 0.5mL tubes are easier to handle/work with.

- PrepAmp Mix was prepared as a master mix and then distributed to samples as required

| PrepAmp_component   | single_rxn_vol(uL) | num_rxns | total_vol(uL) |
|---------------------|--------------------|----------|---------------|
| PrepAmp Buffer (5x) | 1                  | 26       | 26            |
| PrepAmp Pre-mix     | 3.75               | 26       | 97.5          |
| PrepAmp Polymerase  | 0.3                | 26       | 7.8           |

##### SECTION 3

- Elutions consistently returned 1.5uL _less_ volume than input (e.g 12uL input returned 10.5uL).

  - This was also noted [by Shelly when she utilized this kit previously](https://shellytrigg.github.io/122th-post/).

##### SECTION 4

- Recovery from SECTION 3 elution was only 10.5uL (expected 11.5uL based on protocol), so added 1.5uL H<sub>2</sub>O to each sample.

- Based on input DNA range (1ng - 50ng), number of cycles was set to 8.

##### SECTION 5

- Anticipating the loss in elution volume, samples were eluted with 13.5uL in the preceding cleanup step and yielded 12uL (the target input volume for this section).

---

NOTE: Sample `CH10-19` had a weird elution in SECTION 4 - only recovered 6.5uL. Brought volume up to 12uL with H<sub>2</sub>O for required input volume in SECTION 5.

Next step, run the samples on the Bioanalyzer for QC to see how they look.



##### Sample - Sequencing Primer Index Table

| Sample  | Illumina_TruSeq_index_num | Illumina_TruSeq_Index_seq | SRID/ZymoID |
|---------|---------------------------|---------------------------|-------------|
| CH01-06 | 1                         | CGTGAT                    | 1732        |
| CH01-14 | 2                         | CGATGT                    | A           |
| CH01-22 | 3                         | GCCTAA                    | 1731        |
| CH01-38 | 4                         | TGACCA                    | B           |
| CH03-04 | 5                         | ACAGTG                    | C           |
| CH03-15 | 6                         | GCCAAT                    | D           |
| CH03-33 | 7                         | CAGATC                    | E           |
| CH05-01 | 8                         | TCAAGT                    | 1730        |
| CH05-06 | 9                         | CTGATC                    | 1729        |
| CH05-21 | 10                        | AAGCTA                    | 1728        |
| CH05-24 | 11                        | GTAGCC                    | 1727        |
| CH05-26 | 12                        | CTTGTA                    | F           |
| CH07-06 | 13                        | TTGACT                    | 1726        |
| CH07-11 | 14                        | GGAACT                    | 1725        |
| CH07-24 | 15                        | TGACAT                    | 1724        |
| CH09-02 | 16                        | GGACGG                    | 1723        |
| CH09-11 | 17                        | CTCTAC                    | 1722        |
| CH09-13 | 18                        | GCGGAC                    | 1721        |
| CH09-28 | 19                        | TTTCAC                    | 1720        |
| CH09-29 | 20                        | GGCCAC                    | 1719        |
| CH10-01 | 21                        | CGAAAC                    | 1718        |
| CH10-08 | 22                        | CGTACG                    | 1717        |
| CH10-11 | 23                        | CCACTC                    | 1805        |
| CH10-19 | 25                        | ATCAGT                    | 1804        |

All sample processing info/history can currently be found here (Google Sheet):

- [OA Crab Sample Collection 071119](https://docs.google.com/spreadsheets/d/1ym0XnYVts98tIUCn0kIaU6VuvqxzV7LoSx9RHwLdiIs/edit?usp=sharing)

Any additional project info will end up in this GitHub repo:

- [project-dungeness-crab](https://github.com/RobertsLab/project-dungeness-crab)
