---
layout: post
title: Daily Bits - December 2022
date: '2022-12-01 07:23'
tags: 
  - daily bits
categories: 
  - Daily Bits
---

20221227

- Read Ch.10 of "The Disordered Cosmos."

---

20221221

- Added transcriptome assembly info to [The Handbook](https://robertslab.github.io/resources/bio_Transcriptome-assembly/).

---

20221219

- Finished notebook entries for [Haws `epidiverse/snp` analysis using default config](https://robertslab.github.io/sams-notebook/2022/12/14/BS-Seq-Analysis-Nextflow-EpiDiverse-SNP-Pipeline-for-Haws-Hawaii-C.gigas-BAMs-from-Yaamini.html), as well as a [run with a modified config file](https://robertslab.github.io/sams-notebook/2022/12/15/BS-Seq-Analysis-Nextflow-EpiDiverse-SNP-Pipeline-for-Haws-Hawaii-C.gigas-BAMs-from-Yaamini-Base-Config.html) to compare runtimes. Spoiler: Default config file is significantly faster (less than half the runtime) than the modified config file I created.

- Lab meeting:

  - Matt talked about ANOVA stuff.

    - Provided [helpful guide he wrote up](https://mattgeorgephd.github.io/ANOVA-guide/).

---

20221216

- Science Hour

  - Looked through plottin Aidan's crab data with Steven.

  - Steven eventually utilized Weka machine learning to mess around wih Aidan's data, too.

---

20221215

- Ran `epidiverse/snp` pipeline on [Haws' lab _C.gigas_ Hawaii BAM files for Yaamini](https://github.com/RobertsLab/resources/issues/1558). using the base config file to compare runtime to the modified config file I used yesterday.

  - This actually completed in 12hrs, whereas the run using the modified config file took ~31hrs...

- Pub-a-thon

---

20221214

- Got `epidiverse/snp` pipeline on [Haws' lab _C.gigas_ Hawaii BAM files for Yaamini](https://github.com/RobertsLab/resources/issues/1558).

---

20221213

- Mox maintenance today slowed effort to run some jobs.

- Worked on getting script/config files ready to run `epidiverse/snp` pipeline on [Haws' lab _C.gigas_ Hawaii BAM files for Yaamini](https://github.com/RobertsLab/resources/issues/1558).

---

20221213

- Read Ch.9 of "The Disordered Cosmos" for lab meeting.

- Lab meeting.

---

20221209

- Science Hour

  - Worked extensively with Olivia and Steven regarding her citrate synthase assay data and analysis.

---

20221208

- Participated in Katie Lotterhos workshop for designing Apps from Google Sheets.

- Met with Linda Rhodes to discuss future of projects.

  - Decision to cancel weekly meetings - will utilize GitHub issues instead.

  - I'm going to try to figure out why new Silva 138 database doesn't work as well as the old 132, in her pipeline.

20221207

- Finally resolved [CEABIGR mean methylation coefficient of methylation calcs](https://github.com/sr320/ceabigr/blob/main/code/40-gene-methylation.Rmd) (GitHub; R Markdown)! And, I figured it out in a very satisfactory, clean way! Looks great, easy to read, easy to follow, and concise.

---

20221202

- Worked on CEABIGR mean methylation coefficient of variation stuff - getting frustrating, but getting closer!

- Science Hour

- CEABIGR meeting with Sam Brogan and Steven.

---

20221201

- Worked on CEABIGR mean methylation coefficient of variation stuff - getting frustrating, but getting closer!

- Helped Emma for awhile troubleshooting an issue with [`TrimGalore`](https://github.com/FelixKrueger/TrimGalore).


