---
layout: post
title: SRA Submission - Ostrea lurida MBD BS-seq from 20160203
date: '2022-06-15 10:18'
tags: 
  - Ostrea lurida
  - Olympia oyster
  - MBD
  - BSseq
  - SRA
categories: 
  - SRA Submission
---
Submitted our [_Ostrea lurida_ (Olympia oyster)](http://en.wikipedia.org/wiki/Pacific_oyster) MBD BS-seq data [from 20160203](https://robertslab.github.io/sams-notebook/2016/02/03/data-received-ostrea-lurida-mbd-enriched-bs-seq.html) to the [NCBI Sequence Read Archive (SRA)](https://www.ncbi.nlm.nih.gov/sra).

I submitted the [concatenated sets of raw data for this project](https://robertslab.github.io/sams-notebook/2016/04/11/data-management-concatenate-fastq-files-from-oly-mbdseq-project.html), so that is why there is only a single FastQ for each sample, as opposed to _six_ FastQs per sample.

Full summary of the experiment(s) associated with this data can be found in [this GitHub repo wiki](https://github.com/RobertsLab/project-olympia.oyster-genomic/wiki/MBD-BSseq-December-2015).

For citing this data, NCBI SRA suggests using the BioProject ID.

| library_ID | bioproject_accession                                               | accession                                                         | study                                                         | biosample_accession                                                 | filename                                                                                                       |
|------------|--------------------------------------------------------------------|-------------------------------------------------------------------|---------------------------------------------------------------|---------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------|
| hc1_2B     | [PRJNA849214](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA849214) | [SRR19653526](https://www.ncbi.nlm.nih.gov/sra/?term=SRR19653526) | [SRP380210](https://www.ncbi.nlm.nih.gov/sra/?term=SRP380210) | [SAMN29043785](https://www.ncbi.nlm.nih.gov/sra/?term=SAMN29043785) | [zr1394_1.fastq.gz](https://owl.fish.washington.edu/nightingales/O_lurida/20160203_mbdseq/zr1394_1.fastq.gz)   |
| hc1_4B     | [PRJNA849214](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA849214) | [SRR19653525](https://www.ncbi.nlm.nih.gov/sra/?term=SRR19653525) | [SRP380210](https://www.ncbi.nlm.nih.gov/sra/?term=SRP380210) | [SAMN29043786](https://www.ncbi.nlm.nih.gov/sra/?term=SAMN29043786) | [zr1394_2.fastq.gz](https://owl.fish.washington.edu/nightingales/O_lurida/20160203_mbdseq/zr1394_2.fastq.gz)   |
| hc2_15B    | [PRJNA849214](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA849214) | [SRR19653516](https://www.ncbi.nlm.nih.gov/sra/?term=SRR19653516) | [SRP380210](https://www.ncbi.nlm.nih.gov/sra/?term=SRP380210) | [SAMN29043787](https://www.ncbi.nlm.nih.gov/sra/?term=SAMN29043787) | [zr1394_3.fastq.gz](https://owl.fish.washington.edu/nightingales/O_lurida/20160203_mbdseq/zr1394_3.fastq.gz)   |
| hc2_17     | [PRJNA849214](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA849214) | [SRR19653515](https://www.ncbi.nlm.nih.gov/sra/?term=SRR19653515) | [SRP380210](https://www.ncbi.nlm.nih.gov/sra/?term=SRP380210) | [SAMN29043788](https://www.ncbi.nlm.nih.gov/sra/?term=SAMN29043788) | [zr1394_4.fastq.gz](https://owl.fish.washington.edu/nightingales/O_lurida/20160203_mbdseq/zr1394_4.fastq.gz)   |
| hc3_1      | [PRJNA849214](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA849214) | [SRR19653514](https://www.ncbi.nlm.nih.gov/sra/?term=SRR19653514) | [SRP380210](https://www.ncbi.nlm.nih.gov/sra/?term=SRP380210) | [SAMN29043789](https://www.ncbi.nlm.nih.gov/sra/?term=SAMN29043789) | [zr1394_5.fastq.gz](https://owl.fish.washington.edu/nightingales/O_lurida/20160203_mbdseq/zr1394_5.fastq.gz)   |
| hc3_5      | [PRJNA849214](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA849214) | [SRR19653513](https://www.ncbi.nlm.nih.gov/sra/?term=SRR19653513) | [SRP380210](https://www.ncbi.nlm.nih.gov/sra/?term=SRP380210) | [SAMN29043790](https://www.ncbi.nlm.nih.gov/sra/?term=SAMN29043790) | [zr1394_6.fastq.gz](https://owl.fish.washington.edu/nightingales/O_lurida/20160203_mbdseq/zr1394_6.fastq.gz)   |
| hc3_7      | [PRJNA849214](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA849214) | [SRR19653512](https://www.ncbi.nlm.nih.gov/sra/?term=SRR19653512) | [SRP380210](https://www.ncbi.nlm.nih.gov/sra/?term=SRP380210) | [SAMN29043791](https://www.ncbi.nlm.nih.gov/sra/?term=SAMN29043791) | [zr1394_7.fastq.gz](https://owl.fish.washington.edu/nightingales/O_lurida/20160203_mbdseq/zr1394_7.fastq.gz)   |
| hc3_10     | [PRJNA849214](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA849214) | [SRR19653511](https://www.ncbi.nlm.nih.gov/sra/?term=SRR19653511) | [SRP380210](https://www.ncbi.nlm.nih.gov/sra/?term=SRP380210) | [SAMN29043792](https://www.ncbi.nlm.nih.gov/sra/?term=SAMN29043792) | [zr1394_8.fastq.gz](https://owl.fish.washington.edu/nightingales/O_lurida/20160203_mbdseq/zr1394_8.fastq.gz)   |
| hc3_11     | [PRJNA849214](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA849214) | [SRR19653510](https://www.ncbi.nlm.nih.gov/sra/?term=SRR19653510) | [SRP380210](https://www.ncbi.nlm.nih.gov/sra/?term=SRP380210) | [SAMN29043793](https://www.ncbi.nlm.nih.gov/sra/?term=SAMN29043793) | [zr1394_9.fastq.gz](https://owl.fish.washington.edu/nightingales/O_lurida/20160203_mbdseq/zr1394_9.fastq.gz)   |
| ss2_9B     | [PRJNA849214](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA849214) | [SRR19653509](https://www.ncbi.nlm.nih.gov/sra/?term=SRR19653509) | [SRP380210](https://www.ncbi.nlm.nih.gov/sra/?term=SRP380210) | [SAMN29043794](https://www.ncbi.nlm.nih.gov/sra/?term=SAMN29043794) | [zr1394_10.fastq.gz](https://owl.fish.washington.edu/nightingales/O_lurida/20160203_mbdseq/zr1394_10.fastq.gz) |
| ss2_14B    | [PRJNA849214](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA849214) | [SRR19653524](https://www.ncbi.nlm.nih.gov/sra/?term=SRR19653524) | [SRP380210](https://www.ncbi.nlm.nih.gov/sra/?term=SRP380210) | [SAMN29043795](https://www.ncbi.nlm.nih.gov/sra/?term=SAMN29043795) | [zr1394_11.fastq.gz](https://owl.fish.washington.edu/nightingales/O_lurida/20160203_mbdseq/zr1394_11.fastq.gz) |
| ss2_18B    | [PRJNA849214](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA849214) | [SRR19653523](https://www.ncbi.nlm.nih.gov/sra/?term=SRR19653523) | [SRP380210](https://www.ncbi.nlm.nih.gov/sra/?term=SRP380210) | [SAMN29043796](https://www.ncbi.nlm.nih.gov/sra/?term=SAMN29043796) | [zr1394_12.fastq.gz](https://owl.fish.washington.edu/nightingales/O_lurida/20160203_mbdseq/zr1394_12.fastq.gz) |
| ss3_3B     | [PRJNA849214](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA849214) | [SRR19653522](https://www.ncbi.nlm.nih.gov/sra/?term=SRR19653522) | [SRP380210](https://www.ncbi.nlm.nih.gov/sra/?term=SRP380210) | [SAMN29043797](https://www.ncbi.nlm.nih.gov/sra/?term=SAMN29043797) | [zr1394_13.fastq.gz](https://owl.fish.washington.edu/nightingales/O_lurida/20160203_mbdseq/zr1394_13.fastq.gz) |
| ss3_14B    | [PRJNA849214](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA849214) | [SRR19653521](https://www.ncbi.nlm.nih.gov/sra/?term=SRR19653521) | [SRP380210](https://www.ncbi.nlm.nih.gov/sra/?term=SRP380210) | [SAMN29043798](https://www.ncbi.nlm.nih.gov/sra/?term=SAMN29043798) | [zr1394_14.fastq.gz](https://owl.fish.washington.edu/nightingales/O_lurida/20160203_mbdseq/zr1394_14.fastq.gz) |
| ss3_15B    | [PRJNA849214](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA849214) | [SRR19653520](https://www.ncbi.nlm.nih.gov/sra/?term=SRR19653520) | [SRP380210](https://www.ncbi.nlm.nih.gov/sra/?term=SRP380210) | [SAMN29043799](https://www.ncbi.nlm.nih.gov/sra/?term=SAMN29043799) | [zr1394_15.fastq.gz](https://owl.fish.washington.edu/nightingales/O_lurida/20160203_mbdseq/zr1394_15.fastq.gz) |
| ss3_16B    | [PRJNA849214](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA849214) | [SRR19653519](https://www.ncbi.nlm.nih.gov/sra/?term=SRR19653519) | [SRP380210](https://www.ncbi.nlm.nih.gov/sra/?term=SRP380210) | [SAMN29043800](https://www.ncbi.nlm.nih.gov/sra/?term=SAMN29043800) | [zr1394_16.fastq.gz](https://owl.fish.washington.edu/nightingales/O_lurida/20160203_mbdseq/zr1394_16.fastq.gz) |
| ss3_20     | [PRJNA849214](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA849214) | [SRR19653518](https://www.ncbi.nlm.nih.gov/sra/?term=SRR19653518) | [SRP380210](https://www.ncbi.nlm.nih.gov/sra/?term=SRP380210) | [SAMN29043801](https://www.ncbi.nlm.nih.gov/sra/?term=SAMN29043801) | [zr1394_17.fastq.gz](https://owl.fish.washington.edu/nightingales/O_lurida/20160203_mbdseq/zr1394_17.fastq.gz) |
| ss5_18     | [PRJNA849214](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA849214) | [SRR19653517](https://www.ncbi.nlm.nih.gov/sra/?term=SRR19653517) | [SRP380210](https://www.ncbi.nlm.nih.gov/sra/?term=SRP380210) | [SAMN29043802](https://www.ncbi.nlm.nih.gov/sra/?term=SAMN29043802) | [zr1394_18.fastq.gz](https://owl.fish.washington.edu/nightingales/O_lurida/20160203_mbdseq/zr1394_18.fastq.gz) |