---
layout: post
title: DNA Isolation and Quantification - C.bairdi Hemolymph Pellets in RNAlater
date: '2020-01-17 14:46'
tags:
  - Chionoecetes bairdi
  - Tanner crab
  - DNA
  - DNA isolation
  - DNA quantification
  - Qubit
categories:
  - 2020
  - Miscellaneous
---

Isolated DNA from the following 23 samples:

-  6128_112_9
-  6204_114_9
-  6141_123_9
-  6245_126_9
-  6240_134_9
-  6260_136_9
-  6257_138_9
-  6259_139_9
-  6258_140_9
-  6255_143_9
-  6256_146_9
-  6265_155_9
-  6266_156_9
-  6261_164_9
-  6120_165_9
-  6251_167_9
-  6262_168_9
-  6243_173_9
-  6263_179_9
-  6264_180_9
-  6200_208_12
-  6204_252_12
-  6190_256_12


Isolated DNA using the [Quick DNA/RNA Microprep Kit](https://github.com/RobertsLab/resources/blob/master/protocols/Commercial_Protocols/ZymoResearch_quick-dna-rna_microprep_plus_kit_20190411.pdf) (ZymoResearch; PDF) according to the manufacturer's protocol for liquids/cells in RNAlater.

- Used 35uL from each RNAlater/hemocyte slurry.

- Mixed with equal volume of H<sub>2</sub>O (35uL).

- Retained DNA on the Zymo-Spin IC-XM columns for isolation after RNA isolation.

- DNA was eluted in 15uL H<sub>2</sub>O

DNA was quantified on the Roberts Lab Qubit 3.0 using the 1x DNA High Sensitivity Assay (Invitrogen), using 2uL of each sample.

Two samples were too concentrated, so those two samples were re-quantified using 1uL of sample.

---

#### RESULTS

Qubit results (Google Sheet):

- [20200117_qubit_cbai_DNA](https://docs.google.com/spreadsheets/d/12pVDjM5EkiPHdcILZBhZsn9m4ftXfVy8SC5rUr9zySM/edit?usp=sharing)

Got DNA from all samples, despite the fact that [I didn't get any RNA from them...](https://robertslab.github.io/sams-notebook/2020/01/17/RNA-Isolation-and-Quantification-C.bairdi-Hemolymph-Pellets-in-RNAlater.html)

Samples were stored at -80<sup>o</sup>C in:

[Rack 6, 4, 1](http://b.link/srlab-80C) in [C.bairdi gDNA Box #1](https://docs.google.com/spreadsheets/d/1D09mPvwDReuUNR36p_BrlrNfev_Ko1F83W4EKdAO6bk/edit?usp=sharing)
