---
layout: post
title: Data Received - C.gigas Ploidy WGBS from Ronits Project via ZymoResearch
date: '2020-11-10 11:08'
tags:
  - Crassostrea gigas
  - Pacific oyster
  - wgbs
  - Zymo
  - ZymoResearch
  - BSseq
categories:
  - Data received
---
We received the data from our [whole genome bisulfite sequencing (WGBS) submission to ZymoResearch on 2020820](https://robertslab.github.io/sams-notebook/2020/08/20/Samples-Submitted-Ronits-C.gigas-Diploid-and-Triploid-Ctenidia-to-ZymoResearch-for-WGBS.html) for Ronit's _C.gigas_ diploid/triploid dessication/heat stress project.

Samples were sequenced using 150bp paired-end, on the Illumina NovaSeq.

Files have been added to [the C.gigas folder in nightingales on Owl (Synology server)](https://owl.fish.washington.edu/nightingales/C_gigas/).

I've updated the [nightingales Google Sheet database as well](https://docs.google.com/spreadsheets/d/1_XqIOPVHSBVGscnjzDSWUeRL7HUHXfaHxVzec-I-8Xk/edit?usp=sharing).

Next up:

- Run FatQC

- Submit to NCBI sequence read archive (SRA).


| SeqID     | Library_Name | Tissue   | Ploidy   | Dessication | Heat_Stress |
|-----------|--------------|----------|----------|-------------|-------------|
| zr3534_1  | D11-C        | ctenidia | diploid  | yes         | no          |
| zr3534_2  | D12-C        | ctenidia | diploid  | yes         | no          |
| zr3534_3  | D13-C        | ctenidia | diploid  | yes         | no          |
| zr3534_4  | D19-C        | ctenidia | diploid  | yes         | yes         |
| zr3534_5  | D20-C        | ctenidia | diploid  | yes         | yes         |
| zr3534_6  | T11-C        | ctenidia | triploid | yes         | no          |
| zr3534_7  | T12-C        | ctenidia | triploid | yes         | no          |
| zr3534_8  | T13-C        | ctenidia | triploid | yes         | no          |
| zr3534_9  | T19-C        | ctenidia | triploid | yes         | yes         |
| zr3534_10 | T20-C        | ctenidia | triploid | yes         | yes         |
