---
layout: post
title: DNA Isolation and Quantification - C.gigas High-Low pH Triploid and Diploid Ctenidia
date: '2020-08-21 13:30'
tags:
  - DNA isolation
  - triploid
  - diploid
  - ctenidia
  - Crasostrea gigas
  - Pacific oyster
categories:
  - Miscellaneous
---
Isolated DNA from 24 of the _Crassostrea gigas_ high/low pH triploid/diploid ctenidia samples [that we received yesterday from the Haws Lab](https://robertslab.github.io/sams-notebook/2020/08/20/Samples-Received-C.gigas-High-Low-pH-Triploid-Diploid-from-Maria-Haws-Lab.html). Samples selected by Steven.

As noted yesterday, the samples appeared to be very liquid-y, so I spun them down for 1min @ 10,000g to help pellet the tissue. Discarded as much supernatant as possible. Isolated DNA using the E.Z.N.A. Mollusc Kit (Omega), according to the manufacturer's protocol with the following changes/notes (no option steps were performed):

- incubated O/N @ 37<sup>o</sup>C

- eluted with 100uL of Elution Buffer

Of note, upon initial addition of the lysis buffer (MBL1), a thick, white precipitate formed immediately. Vortexing seemed to help emulsify this. However, upon retrieving the samples the next day, the sample appeared the same, with the thick, white precipitate sitting on top of the rest of the liquid. Many of the samples did not fully lyse.

DNA was quantified using the Roberts Lab Qubit 3.0 and the ds DNA BR Assay (Invitrogen), using 2uL of each sample.

UPDATE: It turns out the samples were preserved in DNA/RNA Shield (ZymoResearch)! I was not informed of this prior to my inquiry as to why all of the samples seemed to have so much liquid, when I was simply expecting frozen tissue.

---

#### RESULTS

Qubit results:

- [20200821_qubit_gDNA_cgigas_hawaii_ploidy_pH](https://docs.google.com/spreadsheets/d/1PzL110GOgXzEN5mVIWNpBqMD2Dl5Ib7ZHyaNSn-i6ZI/edit?usp=sharing) (Google Sheet)

Yields look good. So, good to know that DNA/RNA Shield doesn't seem to have an impact on DNA isolations performed with the E.Z.N.A. Mollusc Kit!

Samples were stored @ -20<sup>o</sup>C in [Sam's gDNA Box #3](https://docs.google.com/spreadsheets/d/16n4LzVNXrMd3fYRHN4UR4CQ67yRXwlJfDiAmbxD284g/edit?usp=sharing), positions F4 - H9.

| Sample_ID | Concentration(ng/uL) | Volume(uL) | Total_DNA(ng) |
|-----------|----------------------|------------|---------------|
| 2N_HI_5   | 40.4                 | 100        | 4040          |
| 2N_HI_8   | 11.6                 | 100        | 1160          |
| 2N_HI_9   | 32.3                 | 100        | 3230          |
| 2N_HI_10  | 61                   | 100        | 6100          |
| 2N_HI_11  | 21                   | 100        | 2100          |
| 2N_HI_12  | 11.2                 | 100        | 1120          |
| 2N_LOW_1  | 32.1                 | 100        | 3210          |
| 2N_LOW_2  | 32.5                 | 100        | 3250          |
| 2N_LOW_3  | 36                   | 100        | 3600          |
| 2N_LOW_4  | 40.2                 | 100        | 4020          |
| 2N_LOW_5  | 17.8                 | 100        | 1780          |
| 2N_LOW_6  | 22.8                 | 100        | 2280          |
| 3N_HI_2   | 29.6                 | 100        | 2960          |
| 3N_HI_3   | 71.8                 | 100        | 7180          |
| 3N_HI_5   | 29.3                 | 100        | 2930          |
| 3N_HI_8   | 38.9                 | 100        | 3890          |
| 3N_HI_10  | 38.3                 | 100        | 3830          |
| 3N_HI_11  | 52.3                 | 100        | 5230          |
| 3N_LOW_6  | 35.3                 | 100        | 3530          |
| 3N_LOW_7  | 43.6                 | 100        | 4360          |
| 3N_LOW_8  | 63.9                 | 100        | 6390          |
| 3N_LOW_10 | 54.4                 | 100        | 5440          |
| 3N_LOW_11 | 50.8                 | 100        | 5080          |
| 3N_LOW_12 | 52                   | 100        | 5200          |
