---
layout: post
title: Data Management - E5 Coral RNA-seq and sRNA-seq Reorganizing and Renaming
date: '2023-05-17 07:35'
tags: 
  - E5
  - coral
  - RNAseq
  - sRNAseq
categories: 
  - 2023
  - Data Management
---
Downloaded the E5 coral sRNA-seq data from Azenta project 30-852430235 on [20230515](https://robertslab.github.io/sams-notebook/posts/2023/2023-05-15-Data-Received-Coral-sRNA-seq-Data-from-Azenta-Project-30-852430235.html) and the E5 coral RNA-seq data from Azenta project 30-789513166  on [20230516](https://robertslab.github.io/sams-notebook/2023/05/16/Data-Received-Coral-RNA-seq-Data-from-Azenta-Project-30-789513166.html). The data required some reorganization, as the project included data from three different species (_Acropora pulchra_, _Pocillopora meandrina_, and _Porites evermanni_). Additionally, since the project was sequencing the same exact samples with both RNA-seq and sRNA-seq, the resulting FastQ files ended up being the same. This fact seemed like it could lead to potential downstream mistakes and/or difficulty tracking whether or not someone was actually using an RNA-seq or an sRNA-seq FastQ./

With all of this in mind, I performed the following tasks:

- Copied and renamed RNA/sRNA-seq FastQs by appending `RNA` or `sRNA` to the beginning of FastQ filenames. I also retained the original FastQ files. NOTE: The renaming process does _not_ alter the MD5 checksum, so the renamed files can still be "tracked" by comparing checksums with the originals if needed.

- Created species directories on Owl.

- Created Azenta project subdirectories within each species directory.

- Updated [`Nightingales`](https://b.link/nightingales) (Google Sheet) database


---

#### RESULTS

Output folders:

- [https://owl.fish.washington.edu/nightingales/A_pulchra/30-789513166/](https://owl.fish.washington.edu/nightingales/A_pulchra/30-789513166/)

- [https://owl.fish.washington.edu/nightingales/A_pulchra/30-852430235/](https://owl.fish.washington.edu/nightingales/A_pulchra/30-852430235/)

- [https://owl.fish.washington.edu/nightingales/P_meandrina/30-789513166/](https://owl.fish.washington.edu/nightingales/P_meandrina/30-789513166/)

- [https://owl.fish.washington.edu/nightingales/P_meandrina/30-852430235/](https://owl.fish.washington.edu/nightingales/P_meandrina/30-852430235/)

- [https://owl.fish.washington.edu/nightingales/P_evermanni/30-789513166/](https://owl.fish.washington.edu/nightingales/P_evermanni/30-789513166/)

- [https://owl.fish.washington.edu/nightingales/P_evermanni/30-852430235/](https://owl.fish.washington.edu/nightingales/P_evermanni/30-852430235/)

