---
layout: post
title: DNA Isolation and Quantification - C.gigas Diploid (Ronit) and Triploid (Nisbet)
date: '2020-07-22 09:50'
tags:
  - diploid
  - triploid
  - Crassostrea gigas
  - Pacific oyster
  - adductor
  - ctenidia
  - gonad
  - mantle
  - Qubit
  - dsDNA BR assay
categories:
  - Miscellaneous
---
Isolated some gDNA from the [triploid Nisbet oysters we received on 20200218](https://robertslab.github.io/sams-notebook/2018/02/28/samples-received-triploid-crassostrea-gigas-from-nisbet-oyster-company.html) and one of [Ronit's diploid ctenidia samples](https://docs.google.com/spreadsheets/d/1QfEV4wUp3jgChxHhpaYsVswZEem3t3uQATNk4bB_XIU/edit) (Google Sheet) using the E.Z.N.A. Mollusc DNA Kit (Omega). See the "Results" section for sample info.

Samples were pulverized under liquid nitrogen (LN2). Samples were _not_ weighed beforehand; simply "eye-balled" pieces to get close to ~30 - 50mg. [Manufacturer's protocol](https://github.com/RobertsLab/resources/blob/master/protocols/Commercial_Protocols/Omega_Mollusc-DNA-Kit-Combo-May-2013-D3373.pdf) (PDF) was followed with the following notes/changes:

- Proteinase K was _not_ from kit (seem to be out). Instead was ThermoFisher brand (stored in -20C) with a concentration of ~20mg/mL and expiration date of September 2019.

- eluted in 100uL of elution buffer

DNA was quantified using the Roberts Lab Qubit 3.0 using the dsDNA BR Assay (Invitrogen) and 1uL of each sample.

Resulting DNA was stored in [Sam's gDNA Box #3, Positions I4 - I9](https://docs.google.com/spreadsheets/d/1SWzKMKh7LBOgTfvEhJamE6pZFsTpRXY7otzXUC5fZSM/edit?usp=sharing)


---

#### RESULTS

Qubit results (Google Sheet):

- [20200722_qubit_DNA_gigas_ploidy](https://docs.google.com/spreadsheets/d/1JhG0lAn9JjFQgJPjq67cOMrtqDT03nQuNSpRR_i7ojU/edit?usp=sharing)


| Sample             | Original sample conc. (ng/uL) | Elution volume (uL) | Yield (ng) |
|--------------------|-------------------------------|---------------------|------------|
| Nisbet #1 adductor | 50.4                          | 100                 | 5040       |
| Nisbet #1 ctenidia | 80.2                          | 100                 | 8020       |
| Nisbet #1 gonad    | 14.8                          | 100                 | 1480       |
| Nisbet #1 mantle   | 18.8                          | 100                 | 1880       |
| Ronit D05 C2       | 89.4                          | 100                 | 8940       |
| Ronit D04 C        | 97.0                          | 100                 | 9700       |
