---
layout: post
title: Data Wrangling - Create Primary P.generosa Genome Annotation File
date: '2022-04-19 13:20'
tags: 
  - Panopea generosa
  - Pacific geoduck
  - Jupyter
categories: 
  - 2022
  - Miscellaneous
---
[Steven asked me to create a canonical genome annotation file]([GitHub Issue](https://github.com/RobertsLab/resources/issues/1443)) (GitHub Issue). I needed/wanted to create a file containing gene IDs, SwissProt (SP) IDs, gene names, gene descriptions, and gene ontology (GO) accessions. To do so, I utilized the NCBI BLAST and DIAMOND BLAST annotations generated by our [GenSas _P.generosa_ genome annotation](https://robertslab.github.io/sams-notebook/2019/09/28/Genome-Annotation-Pgenerosa_v074-a4-Using-GenSAS.html). Per Steven's suggestion, I used the best match (i.e. lowest `e-value`) for any given gene between the two files.

After doing that, I used the SPIDs to perform a batch retrieval from [UniProt](https://www.uniprot.org/) databases. This batch retrieval pulls down a lengthy annotation file which needed to be parsed to retrieve just the info we want for each SPID. The desired info was then joined with the list of [_Panopea generosa_ (Pacific geoduck)](http://en.wikipedia.org/wiki/Geoduck) genes and the corresponding SPID from the NCBI BLAST and DIAMOND BLAST annotations generated by our [GenSas _P.generosa_ genome annotation](https://robertslab.github.io/sams-notebook/2019/09/28/Genome-Annotation-Pgenerosa_v074-a4-Using-GenSAS.html).

This data wrangling also identified 8 SPID annotations that were obsolete/deleted from UniProt or which redirect to a different SPID. Those SPIDs which are obsolete/deleted were not dealt with further. For those that redirect to a different SPID, the notebook was run to identify these SPIDs and then modified to update the SPID list with these new SPIDs. The notebook was then run a second time to incorporate these updated SPIDs.

The output file is tab-delimited, with the following columns:

- `gene_ID`: Gene ID from our [_Panopea generosa_ (Pacific geoduck)](http://en.wikipedia.org/wiki/Geoduck) genome.

- `SPIDs`: Comma-delimited list of SPIDs from UniProt. One SPID in this list is a match corresponding to the our original BLAST annotations.

- `UniProt_gene_ID`: Gene accession from UniProt.

- `gene`: Abbreviated gene name from UniProt.

- `gene_description`: Human-readable gene description from UniProt.

- `alternate_gene_description`: Human-readable alternate gene description from UniProt.

- `GO_IDs`: GO IDs from UniProt.

All analysis was run in the following Jupyter Notebook:

- [20220419-pgen-gene_annotation_mapping.ipynb](https://github.com/RobertsLab/code/blob/master/notebooks/sam/20220419-pgen-gene_annotation_mapping.ipynb) (GitHub)

- [20220419-pgen-gene_annotation_mapping.ipynb](https://nbviewer.org/github/RobertsLab/code/blob/master/notebooks/sam/20220419-pgen-gene_annotation_mapping.ipynb) (NBViewer)


<iframe src="https://nbviewer.org/github/RobertsLab/code/blob/master/notebooks/sam/20220419-pgen-gene_annotation_mapping.ipynb" width="100%" height="2000" scrolling="yes"></iframe>


---

#### RESULTS

Output folder:

- [20220419-pgen-gene_annotation_mapping/](https://gannet.fish.washington.edu/Atumefaciens/20220419-pgen-gene_annotation_mapping/)

  - Annotation file (3.4MB; text)

    - [20220419-pgen-gene-accessions-gene_id-gene_name-gene_description-alt_gene_description-go_ids.tab](https://gannet.fish.washington.edu/Atumefaciens/20220419-pgen-gene_annotation_mapping/20220419-pgen-gene-accessions-gene_id-gene_name-gene_description-alt_gene_description-go_ids.tab)

Intermediate files, as well as the batch retrieval data from UniProt are available as well. See [directory README file](https://gannet.fish.washington.edu/Atumefaciens/20220419-pgen-gene_annotation_mapping/readme.txt) for more info.