---
layout: post
title: SRA Submission - Haws Lab C.gigas Ploidy pH WGBS
date: '2020-12-07 06:31'
tags:
  - sra
  - ncbi
  - ploidy
  - wgbs
  - haws
  - hawaii
  - Crassostrea gigas
  - Pacific oyster
categories:
  - SRA Submission
---
I submitted the [24 _C.gigas_ diploid/triploid pH-treated WGBS sequence data we received 20201205](https://robertslab.github.io/sams-notebook/2020/12/05/Data-Received-C.gigas-Diploid-Triploid-pH-Treatments-Ctenidia-WGBS-from-ZymoResearch.html) to the [NCBI Sequence Read Archive (SRA)](https://www.ncbi.nlm.nih.gov/sra).

The samples were registered as part of the following BioProject:

- [PRJNA682817](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA682817)

This accession number is what should be referenced for any publications with these samples. This has been added to [`Nightingales`](http://b.link/nightingales) (Google Sheet), the Roberts Lab NGS database.

Here is a table which contains individual sample accession numbers, in case they're needed:

| Sample_ID | BioSample                                                           | BioProject                                                         |
|-----------|---------------------------------------------------------------------|--------------------------------------------------------------------|
| 2N_HI_05  | [SAMN17011249](https://www.ncbi.nlm.nih.gov/biosample/SAMN17011249) | [PRJNA682817](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA682817) |
| 2N_HI_08  | [SAMN17011255](https://www.ncbi.nlm.nih.gov/biosample/SAMN17011255) | [PRJNA682817](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA682817) |
| 2N_HI_09  | [SAMN17011256](https://www.ncbi.nlm.nih.gov/biosample/SAMN17011256) | [PRJNA682817](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA682817) |
| 2N_HI_10  | [SAMN17011257](https://www.ncbi.nlm.nih.gov/biosample/SAMN17011257) | [PRJNA682817](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA682817) |
| 2N_HI_11  | [SAMN17011258](https://www.ncbi.nlm.nih.gov/biosample/SAMN17011258) | [PRJNA682817](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA682817) |
| 2N_HI_12  | [SAMN17011259](https://www.ncbi.nlm.nih.gov/biosample/SAMN17011259) | [PRJNA682817](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA682817) |
| 2N_LOW_01 | [SAMN17011260](https://www.ncbi.nlm.nih.gov/biosample/SAMN17011260) | [PRJNA682817](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA682817) |
| 2N_LOW_02 | [SAMN17011261](https://www.ncbi.nlm.nih.gov/biosample/SAMN17011261) | [PRJNA682817](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA682817) |
| 2N_LOW_03 | [SAMN17011262](https://www.ncbi.nlm.nih.gov/biosample/SAMN17011262) | [PRJNA682817](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA682817) |
| 2N_LOW_04 | [SAMN17011239](https://www.ncbi.nlm.nih.gov/biosample/SAMN17011239) | [PRJNA682817](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA682817) |
| 2N_LOW_05 | [SAMN17011240](https://www.ncbi.nlm.nih.gov/biosample/SAMN17011240) | [PRJNA682817](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA682817) |
| 2N_LOW_06 | [SAMN17011241](https://www.ncbi.nlm.nih.gov/biosample/SAMN17011241) | [PRJNA682817](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA682817) |
| 3N_HI_02  | [SAMN17011242](https://www.ncbi.nlm.nih.gov/biosample/SAMN17011242) | [PRJNA682817](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA682817) |
| 3N_HI_03  | [SAMN17011243](https://www.ncbi.nlm.nih.gov/biosample/SAMN17011243) | [PRJNA682817](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA682817) |
| 3N_HI_05  | [SAMN17011244](https://www.ncbi.nlm.nih.gov/biosample/SAMN17011244) | [PRJNA682817](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA682817) |
| 3N_HI_08  | [SAMN17011245](https://www.ncbi.nlm.nih.gov/biosample/SAMN17011245) | [PRJNA682817](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA682817) |
| 3N_HI_10  | [SAMN17011246](https://www.ncbi.nlm.nih.gov/biosample/SAMN17011246) | [PRJNA682817](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA682817) |
| 3N_HI_11  | [SAMN17011247](https://www.ncbi.nlm.nih.gov/biosample/SAMN17011247) | [PRJNA682817](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA682817) |
| 3N_LOW_06 | [SAMN17011248](https://www.ncbi.nlm.nih.gov/biosample/SAMN17011248) | [PRJNA682817](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA682817) |
| 3N_LOW_07 | [SAMN17011250](https://www.ncbi.nlm.nih.gov/biosample/SAMN17011250) | [PRJNA682817](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA682817) |
| 3N_LOW_08 | [SAMN17011251](https://www.ncbi.nlm.nih.gov/biosample/SAMN17011251) | [PRJNA682817](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA682817) |
| 3N_LOW_10 | [SAMN17011252](https://www.ncbi.nlm.nih.gov/biosample/SAMN17011252) | [PRJNA682817](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA682817) |
| 3N_LOW_11 | [SAMN17011253](https://www.ncbi.nlm.nih.gov/biosample/SAMN17011253) | [PRJNA682817](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA682817) |
| 3N_LOW_12 | [SAMN17011254](https://www.ncbi.nlm.nih.gov/biosample/SAMN17011254) | [PRJNA682817](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA682817) |
