---
layout: post
title: RNA Isolation - M.trossulus Gill and Phenol Gland
date: '2022-01-09 06:40'
tags: 
  - Mytilus trossulus
  -  bay mussel
  - gill
  - phenol gland
  - RNA isolation
  - RNA quantificaition
  - Qubit
categories: 
  - Miscellaneous
---
As part of a mussel project that Matt George has with the [Pacific States Marine Fisheries Commission (PSMFC)](https://www.psmfc.org/), I'm helping by continuing isolating RNA from a relatively large number of samples. The samples are listed/described in [this GitHub Issue](https://github.com/RobertsLab/resources/issues/1352). Today, I isolated RNA from the following samples (the "F" indicates "foot", "PG" indicates "phenol gland", and "G" indicates "gill" tissues):

- T126-G

- T127-G

- T128-G

- T129-G

- T130-G

- T131-G

- T132-G

- T133-G

- T134-G

- T135-G

- T136-G

- T137-G

- T110-F_PG

- T111-F_PG

- T112-F_PG

- T46-F_PG

- T47-F_PG

- T49-F_PG

- T51-F_PG

- T52-F_PG

- T55-F_PG

- T56-F_PG

- T57-F_PG

- T58-F_PG

- T110-G

- T111-G

- T112-G

- T46-G

- T47-G

- T49-G

- T51-G

- T52-G

- T55-G

- T56-G

- T57-G

- T58-G





RNA was isolated using RNAzol RT and the Direct-zol RNA Microprep Kit (ZymoResearch), with the DNase I on-column treatment step. Foot tissues were allowed to partially thaw to allow me to unfold/unbend the foot and dissect the phenol gland (essentially the most distal end of the foot) with a new razor blade. For gill tissue, small portions of frozen gill tissue were removed from tubes, placed in RNAzol RT and immediately homoegnized. Forceps were rinsed in distilled H<sub>2</sub>O, soaked in 10% bleach solution for 10mins, and then rinsed in distilled H<sub>2</sub>O before re-use. All centrifugation steps were performed at 16,000g for 1.5mins. Here's a brief overview of the process.

Tissues were homogenized in 500uL of TriReagent with "disposable" platic mortar/pestle tubes (1.5mL). After homogenization, an additional 500uL of TriReagent was added to the tube, vortexed and incubated at RT for 10mins. Insoluble debris was pelleted and supernatant was transferred to a 2.0mL tube. An equal volume (1mL) of 100% ethanol was added to this supernatant and mixed thoroughly by pipetting. Direct-zol Microprep Kit protocol was followed from here on, including on-column DNase I treatment. All samples were eluted with 100uL of H<sub>2</sub>O.

RNA was quantified using the Roberts Lab Qubit 3.0 using the Qubit RNA High Sensitivity assay.

All RNA was stored @ -80<sup>o</sup>C in [Sam's RNA Box #2](https://docs.google.com/spreadsheets/d/1jL9gOqtcHrm8JPUtZ5KShpX7_olFuci_5Gq7xqgZKIM/edit?usp=sharing) and [Sam's RNA Box #3](https://docs.google.com/spreadsheets/d/1j9jm3b91IkVfG0EsSjQpR--t2R97YXEQPaOFqsOqjhc/edit?usp=sharing).

---

#### RESULTS

Raw Qubit data (Google Sheet):

- [20220109_qubit_rna_mtro](https://docs.google.com/spreadsheets/d/1wwbogjqb_kiCNOiJdVHgx9A_GqkBSP63AP5GTQWyBTw/edit?usp=sharing)

Virtually all isolations looked good, except `T47-F_PG`, which had an extremely low yield (only 278ng). Not sure what went wrong here, as I don't recall have any specific difficulties with the isolation (e.g. clogged column). Will keep this sample in mind and will likely return to it at a later date, but will let that decision belong to Matt George after he makes decisions regarding sequencing for this project.

Summary Table:

| sample    | tissue       | concentration(ng/uL) | volume(uL) | yield(ng) |
|-----------|--------------|----------------------|------------|-----------|
| T126-G    | gill         | 79                   | 100        | 7900      |
| T127-G    | gill         | 86.6                 | 100        | 8660      |
| T128-G    | gill         | 82                   | 100        | 8200      |
| T129-G    | gill         | 45.8                 | 100        | 4580      |
| T130-G    | gill         | 62.6                 | 100        | 6260      |
| T131-G    | gill         | 31                   | 100        | 3100      |
| T132-G    | gill         | 94.8                 | 100        | 9480      |
| T133-G    | gill         | 56                   | 100        | 5600      |
| T134-G    | gill         | 32.6                 | 100        | 3260      |
| T135-G    | gill         | 44.2                 | 100        | 4420      |
| T136-G    | gill         | 48.6                 | 100        | 4860      |
| T137-G    | gill         | 20.2                 | 100        | 2020      |
| T110-F_PG | phenol gland | 35.6                 | 100        | 3560      |
| T111-F_PG | phenol gland | 29.8                 | 100        | 2980      |
| T112-F_PG | phenol gland | 43.6                 | 100        | 4360      |
| T46-F_PG  | phenol gland | 21.8                 | 100        | 2180      |
| T47-F_PG  | phenol gland | 2.78                 | 100        | 278       |
| T49-F_PG  | phenol gland | 17.4                 | 100        | 1740      |
| T51-F_PG  | phenol gland | 124                  | 100        | 12400     |
| T52-F_PG  | phenol gland | 37                   | 100        | 3700      |
| T55-F_PG  | phenol gland | 32.6                 | 100        | 3260      |
| T56-F_PG  | phenol gland | 64.4                 | 100        | 6440      |
| T57-F_PG  | phenol gland | 91.2                 | 100        | 9120      |
| T58-F_PG  | phenol gland | 28                   | 100        | 2800      |
| T110-G    | gill         | 42.2                 | 100        | 4220      |
| T111-G    | gill         | 40.6                 | 100        | 4060      |
| T112-G    | gill         | 24.2                 | 100        | 2420      |
| T46-G     | gill         | 19.8                 | 100        | 1980      |
| T47-G     | gill         | 47.8                 | 100        | 4780      |
| T49-G     | gill         | 56.6                 | 100        | 5660      |
| T51-G     | gill         | 8.48                 | 100        | 848       |
| T52-G     | gill         | 57.6                 | 100        | 5760      |
| T55-G     | gill         | 56.2                 | 100        | 5620      |
| T56-G     | gill         | 102                  | 100        | 10200     |
| T57-G     | gill         | 112                  | 100        | 11200     |
| T58-G     | gill         | 96.4                 | 100        | 9640      |