---
layout: post
title: RNA Isolation & Quantification - C.bairdi RNA from Sample 6129_403_26
date: '2020-02-10 14:32'
tags:
  - RNA isolation
  - RNA quantification
  - Qubit 3.0
  - hsRNA assay
  - tanner crab
  - Chionoecetes bairdi
categories:
  - Tanner Crab RNAseq
---
Since I was [isolating gDNA from _C.bairdi_ 6129_403_26 hemolymph](https://robertslab.github.io/sams-notebook/2020/02/10/DNA-Isolation-&-Quantification-Additional-C.bairdi-gDNA-from-Sample-6129_403_26.html), I figured I might as well co-isolate RNA since I was using the Quick DNA/RNA Microprep Plus Kit (ZymoResearch).

Followed the manufacturer's protocol with the following notes/changes:

- Used 480uL of sample, combined with 1:1 H<sub>2</sub>O (480uL), with 4:1 Lysis Buffer (3840uL) and mixed in 15mL conical

- Flow-through was retained in a 15mL conical for RNA isolation

- Column began to clog during loading of the initial flow-through + EtOH mixture

- Eluted with 15uL


Quantified on the Roberts Lab Qubit 3.0 using the high-sensitivity RNA Assay (Invitrogen) and 1uL of sample.


---

#### RESULTS

Qubit results (Google Sheet):

- [20200210_qubit_crab_RNA](https://docs.google.com/spreadsheets/d/17HLwzVKPzZlLTBzsrX5XH5t2E8WhztdMlIicPTjr50Q/edit?usp=sharing)

[RNA] = 7.86ng/uL in 15uL

Yield = ~118ng

Yield is very, very low, considering the amount of starting material. Yield is likely due to clogging of column, due to overloading.

Sample was stored at -80<sup>o</sup>C in:

[Rack 2, 3, 5](http://b.link/srlab-80C) in [Shellfish Box #8](https://docs.google.com/spreadsheets/d/1ax6C-muxUTXxFEtfWdswBvueLhmxZzmwZcO2ur-0q-Q/edit#gid=1794729843)
