---
layout: post
title: Daily Bits - October 2022
date: '2022-10-01 10:37'
tags: 
  - daily bits
categories: 
  - 2022
  - Daily Bits
---

20221031

- Lab meeting.

  - Discussed Ch.6 of "The Disordered Cosmos".

- Worked on CEABIGR manuscript in preparation for Friday's meeting with Kaite Lotterhos.


---

20221028

- Science Hour

- Worked heavily on getting CEABIGR max transcript counts Circos formatting.

---

20221027

- Worked on CEABIGR stuff - primarily creating a file of differences in max transcript counts between treatments/sexes for eventual use in Circos.

- Pub-a-thon.

- 16s pipelines are still running! Mox job actually died a little after 1 day of running due a mistake I made in variable naming. Ugh. Restarted late  tonight.

---

20221026

- The 16s pipeline was still running after 24hrs. Decided this was too long, so killed it.

  - Ran Linda Rhodes' 16s pipeline with the reduced 138.99 515-806 primer regions. Should help things move a bit faster.

- Decided to install QIIME2 conda environment on Mox to see if we can speed the pipeline up.

  - Ran a job on Mox with the reduced 138.99 515-806 primer regions to see if this would finish a bit quicker... Still running many hours later...

---

20221025

- Ran Linda Rhodes' 16s pipeline with the "default" 138.99 refseqs/taxonomy. Still running...

---

20221024

- Lab meeting

- Oyster gene expression meeting (had to leave early due to contractors showing up)

- Re-ran Linda Rhodes 16s pipeline with "new" MiSeq data.

  - Used her original SILVA refseq and taxonomy files.

  - Took hours to run on my laptop.

  - Success!! Taxa barplot actually has a majority of reads in each of the samples _assigned_ to Bacteria!!

  - Will now test the SILVA 138.99 refseq and taxonomy files that I generated (followed the QIIME2 guide).


---

20221021

- Dungeness crab genome annotation meeting with NOAA people (Krista, Laura, Mac).

- Met with Linda to discuss weird results.

  - She's retiring at the end of the month, but will continue working on personal computer.

  - She will provide data known to have generated classifications using the pipeline.

  - She'll send me here GitHub username so I can establish a repo to simplify data sharing.

  - I'll schedule recurring meetings to help keep me on task.

- Lotterhos [_Crassostrea virginica_ (Eastern oyster)](https://en.wikipedia.org/wiki/Eastern_oyster) meeting.

---

20221020

- Continued to work on Linda's stuff. Tested her original ref seqs/taxonomy files, but got virtually same results as updated SILVA database/taxonomy (i.e. all samples have no assigned taxonomies)...

---

20221019

- Began to revist Linda Rhode's stuff after negelecting it for an _entire month_??!! Whoa! I literally thought it had only been a couple of weeks... Yeesh.

---

20221018

- Took day off

---

20221017

- Read Ch. 5 of "The Disordered Cosmos"

- Lab meeting - discussed Ch.5 of "The Disordered Cosmos".

- Continued the code/data migration from [2018_L18-adult-methylation repo](https://github.com/epigeneticstoocean/2018_L18-adult-methylation) to CEABIGR repo...

---

20221014

- Continued the code/data migration from [2018_L18-adult-methylation repo](https://github.com/epigeneticstoocean/2018_L18-adult-methylation) to CEABIGR repo...

---

20221013

- Continued the code/data migration from [2018_L18-adult-methylation repo](https://github.com/epigeneticstoocean/2018_L18-adult-methylation) to CEABIGR repo...

20221012

- Continued the code/data migration from [2018_L18-adult-methylation repo](https://github.com/epigeneticstoocean/2018_L18-adult-methylation) to CEABIGR repo...

- Spoke with Matt regarding RNAsequencing options/considerations for _M.trossolus_ transcriptome.

---

20221011

- Worked a a lot on CEABIGR data.

  - Reviewing predominant isoform data, to help clarify some questions Yaamini had.

  - Working on Circos plots; specifically to try to generate something "pretty" for Yaamini to use in her talk at EPIMAR tomorrow.

  - Migrating, and updating, code/data from [2018_L18-adult-methylation repo](https://github.com/epigeneticstoocean/2018_L18-adult-methylation) to CEABIGR repo. Annoying trying to keep track of which scripts/code is in which repo...

---

20221006

- Pub-a-thon

- Continued reorganization of Circos directories within the CEABIGR repo.

- Dealt with weird computer issues throughout the day (VMware Player kept freezing over and over). Potentially resolved by reducing number of CPUs that VM can use?

---

20221005

- Lab cleanup extravaganza

  - Installed 2nd gas cylinder bracket in FTR 213

  - Cleaned up my computer area.

  - Cleaned up my old office.

  - Moved Brent's stuff to FTR 228.

  - Moved Friedman qPCR machine to FTR 228.

  - Helped "clean" up MAR cold room (watched Steven sweep).

---

20221004

- Lab cleanup extravaganza

  - Cleaned out 213 4<sup>o</sup>C fridge

  - Restored T21 table top centrifuge sign up sheet

  - Moved NOAA/Jensen crab bins to FTR 228

  - Evaluated middle freezer in -80<sup>o</sup>C room

  - Fixed FRT 209 printer (ethernet connection had to be enabled in printer settings, despite cable being plugged in).

  - Cleaned my bench.

---

20221003

- Day off