---
layout: post
title: SRA Submission - Geoduck Epigenetic Ocean Acidification RNAseq
date: '2020-07-09 22:22'
tags:
  - sra
  - geoduck
  - Panopea generosa
  - RNAseq
categories:
  - SRA Submission
---
Can't remember where it was discussed (probably lab meeting), but I created a [GitHub Issue to add all of geoduck RNAseq data to NCBI Short Read Archive (SRA)](https://github.com/RobertsLab/resources/issues/963). Anyway, got all the remaining RNAseq data uploaded to the NCBI SRA and organized into the correct BioSamples and BioProjects.

The table below has links to each corresponding NCBI BioSample and BioProject. NCBI indicates that references should point to a particular BioProject; not individual Short Read References (SRR).

I've added the corresponding links to the NCBI BioProjects to our sequencing database, [Nightingales (Google Sheet)](http://b.link/nightingales).

Below is a table sorted by BioProject that also includes links to each BioSample for each "SeqID" (the SeqID is a unique identifier, usually the FastQ filename prefix) used in [Nightingales (Google Sheet)](http://b.link/nightingales).


---

| SeqID                                                        | BioSample                                                   | Tissue   | BioProject                                                         |
|--------------------------------------------------------------|-------------------------------------------------------------|----------|--------------------------------------------------------------------|
| Geoduck-larvae-day5-RNA-EPI-99-1_S8_L001_001                 | [11259647](https://www.ncbi.nlm.nih.gov/biosample/11259647) | larvae   | [PRJNA529226](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA529226) |
| Geoduck-larvae-day5-RNA-EPI-99-2_S16_L002_001                | [11259647](https://www.ncbi.nlm.nih.gov/biosample/11259647) | larvae   | [PRJNA529226](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA529226) |
| Geoduck-larvae-day5-RNA-EPI-99-3_S24_L003_001                | [11259647](https://www.ncbi.nlm.nih.gov/biosample/11259647) | larvae   | [PRJNA529226](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA529226) |
| Geoduck-larvae-day5-RNA-EPI-99-4_S32_L004_001                | [11259647](https://www.ncbi.nlm.nih.gov/biosample/11259647) | larvae   | [PRJNA529226](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA529226) |
| Geoduck-larvae-day5-RNA-EPI-99-5_S40_L005_001                | [11259647](https://www.ncbi.nlm.nih.gov/biosample/11259647) | larvae   | [PRJNA529226](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA529226) |
| Geoduck-larvae-day5-RNA-EPI-99-6_S48_L006_001                | [11259647](https://www.ncbi.nlm.nih.gov/biosample/11259647) | larvae   | [PRJNA529226](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA529226) |
| Geoduck-larvae-day5-RNA-EPI-99-7_S56_L007_001                | [11259647](https://www.ncbi.nlm.nih.gov/biosample/11259647) | larvae   | [PRJNA529226](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA529226) |
| Geoduck-larvae-day5-RNA-EPI-99-8_S64_L008_001                | [11259647](https://www.ncbi.nlm.nih.gov/biosample/11259647) | larvae   | [PRJNA529226](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA529226) |
| Geoduck-juvenile-ambient-exposure-RNA-EPI-123-1_S6_L001_001  | [15517238](https://www.ncbi.nlm.nih.gov/biosample/15517238) | juvenile | [PRJNA566166](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA566166) |
| Geoduck-juvenile-ambient-exposure-RNA-EPI-123-2_S14_L002_001 | [15517238](https://www.ncbi.nlm.nih.gov/biosample/15517238) | juvenile | [PRJNA566166](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA566166) |
| Geoduck-juvenile-ambient-exposure-RNA-EPI-123-3_S22_L003_001 | [15517238](https://www.ncbi.nlm.nih.gov/biosample/15517238) | juvenile | [PRJNA566166](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA566166) |
| Geoduck-juvenile-ambient-exposure-RNA-EPI-123-4_S30_L004_001 | [15517238](https://www.ncbi.nlm.nih.gov/biosample/15517238) | juvenile | [PRJNA566166](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA566166) |
| Geoduck-juvenile-ambient-exposure-RNA-EPI-123-5_S38_L005_001 | [15517238](https://www.ncbi.nlm.nih.gov/biosample/15517238) | juvenile | [PRJNA566166](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA566166) |
| Geoduck-juvenile-ambient-exposure-RNA-EPI-123-6_S46_L006_001 | [15517238](https://www.ncbi.nlm.nih.gov/biosample/15517238) | juvenile | [PRJNA566166](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA566166) |
| Geoduck-juvenile-ambient-exposure-RNA-EPI-123-7_S54_L007_001 | [15517238](https://www.ncbi.nlm.nih.gov/biosample/15517238) | juvenile | [PRJNA566166](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA566166) |
| Geoduck-juvenile-ambient-exposure-RNA-EPI-123-8_S62_L008_001 | [15517238](https://www.ncbi.nlm.nih.gov/biosample/15517238) | juvenile | [PRJNA566166](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA566166) |
| Geoduck-juvenile-ambient-exposure-RNA-EPI-124-1_S7_L001_001  | [15517239](https://www.ncbi.nlm.nih.gov/biosample/15517239) | juvenile | [PRJNA566166](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA566166) |
| Geoduck-juvenile-ambient-exposure-RNA-EPI-124-2_S15_L002_001 | [15517239](https://www.ncbi.nlm.nih.gov/biosample/15517239) | juvenile | [PRJNA566166](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA566166) |
| Geoduck-juvenile-ambient-exposure-RNA-EPI-124-3_S23_L003_001 | [15517239](https://www.ncbi.nlm.nih.gov/biosample/15517239) | juvenile | [PRJNA566166](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA566166) |
| Geoduck-juvenile-ambient-exposure-RNA-EPI-124-4_S31_L004_001 | [15517239](https://www.ncbi.nlm.nih.gov/biosample/15517239) | juvenile | [PRJNA566166](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA566166) |
| Geoduck-juvenile-ambient-exposure-RNA-EPI-124-5_S39_L005_001 | [15517239](https://www.ncbi.nlm.nih.gov/biosample/15517239) | juvenile | [PRJNA566166](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA566166) |
| Geoduck-juvenile-ambient-exposure-RNA-EPI-124-6_S47_L006_001 | [15517239](https://www.ncbi.nlm.nih.gov/biosample/15517239) | juvenile | [PRJNA566166](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA566166) |
| Geoduck-juvenile-ambient-exposure-RNA-EPI-124-7_S55_L007_001 | [15517239](https://www.ncbi.nlm.nih.gov/biosample/15517239) | juvenile | [PRJNA566166](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA566166) |
| Geoduck-juvenile-ambient-exposure-RNA-EPI-124-8_S63_L008_001 | [15517239](https://www.ncbi.nlm.nih.gov/biosample/15517239) | juvenile | [PRJNA566166](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA566166) |
| NR005_S4_L001_001                                            | [15517237](https://www.ncbi.nlm.nih.gov/biosample/15517237) | juvenile | [PRJNA566166](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA566166) |
| NR005_S4_L002_001                                            | [15517237](https://www.ncbi.nlm.nih.gov/biosample/15517237) | juvenile | [PRJNA566166](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA566166) |
| NR019_S7_L001_001                                            | [15517239](https://www.ncbi.nlm.nih.gov/biosample/15517239) | juvenile | [PRJNA566166](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA566166) |
| NR019_S7_L002_001                                            | [15517239](https://www.ncbi.nlm.nih.gov/biosample/15517239) | juvenile | [PRJNA566166](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA566166) |
| Trueseq-stranded-mRNA-libraries-GeoRNA5-E1-NR005_S3_L001     | [15517237](https://www.ncbi.nlm.nih.gov/biosample/15517237) | juvenile | [PRJNA566166](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA566166) |
| Trueseq-stranded-mRNA-libraries-GeoRNA5-E1-NR005_S3_L002     | [15517237](https://www.ncbi.nlm.nih.gov/biosample/15517237) | juvenile | [PRJNA566166](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA566166) |
| Trueseq-stranded-mRNA-libraries-GeoRNA7-G1-NR019_S4_L001     | [15517239](https://www.ncbi.nlm.nih.gov/biosample/15517239) | juvenile | [PRJNA566166](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA566166) |
| Trueseq-stranded-mRNA-libraries-GeoRNA7-G1-NR019_S4_L002     | [15517239](https://www.ncbi.nlm.nih.gov/biosample/15517239) | juvenile | [PRJNA566166](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA566166) |
| Geoduck-juvenile-OA-exposure-RNA-EPI-115-1_S4_L001_001       | [15517236](https://www.ncbi.nlm.nih.gov/biosample/15517236) | juvenile | [PRJNA566166](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA566166) |
| Geoduck-juvenile-OA-exposure-RNA-EPI-115-2_S12_L002_001      | [15517236](https://www.ncbi.nlm.nih.gov/biosample/15517236) | juvenile | [PRJNA566166](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA566166) |
| Geoduck-juvenile-OA-exposure-RNA-EPI-115-3_S20_L003_001      | [15517236](https://www.ncbi.nlm.nih.gov/biosample/15517236) | juvenile | [PRJNA566166](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA566166) |
| Geoduck-juvenile-OA-exposure-RNA-EPI-115-4_S28_L004_001      | [15517236](https://www.ncbi.nlm.nih.gov/biosample/15517236) | juvenile | [PRJNA566166](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA566166) |
| Geoduck-juvenile-OA-exposure-RNA-EPI-115-5_S36_L005_001      | [15517236](https://www.ncbi.nlm.nih.gov/biosample/15517236) | juvenile | [PRJNA566166](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA566166) |
| Geoduck-juvenile-OA-exposure-RNA-EPI-115-6_S44_L006_001      | [15517236](https://www.ncbi.nlm.nih.gov/biosample/15517236) | juvenile | [PRJNA566166](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA566166) |
| Geoduck-juvenile-OA-exposure-RNA-EPI-115-7_S52_L007_001      | [15517236](https://www.ncbi.nlm.nih.gov/biosample/15517236) | juvenile | [PRJNA566166](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA566166) |
| Geoduck-juvenile-OA-exposure-RNA-EPI-115-8_S60_L008_001      | [15517236](https://www.ncbi.nlm.nih.gov/biosample/15517236) | juvenile | [PRJNA566166](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA566166) |
| Geoduck-juvenile-OA-exposure-RNA-EPI-116-1_S5_L001_001       | [15517237](https://www.ncbi.nlm.nih.gov/biosample/15517237) | juvenile | [PRJNA566166](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA566166) |
| Geoduck-juvenile-OA-exposure-RNA-EPI-116-2_S13_L002_001      | [15517237](https://www.ncbi.nlm.nih.gov/biosample/15517237) | juvenile | [PRJNA566166](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA566166) |
| Geoduck-juvenile-OA-exposure-RNA-EPI-116-3_S21_L003_001      | [15517237](https://www.ncbi.nlm.nih.gov/biosample/15517237) | juvenile | [PRJNA566166](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA566166) |
| Geoduck-juvenile-OA-exposure-RNA-EPI-116-4_S29_L004_001      | [15517237](https://www.ncbi.nlm.nih.gov/biosample/15517237) | juvenile | [PRJNA566166](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA566166) |
| Geoduck-juvenile-OA-exposure-RNA-EPI-116-5_S37_L005_001      | [15517237](https://www.ncbi.nlm.nih.gov/biosample/15517237) | juvenile | [PRJNA566166](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA566166) |
| Geoduck-juvenile-OA-exposure-RNA-EPI-116-6_S45_L006_001      | [15517237](https://www.ncbi.nlm.nih.gov/biosample/15517237) | juvenile | [PRJNA566166](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA566166) |
| Geoduck-juvenile-OA-exposure-RNA-EPI-116-7_S53_L007_001      | [15517237](https://www.ncbi.nlm.nih.gov/biosample/15517237) | juvenile | [PRJNA566166](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA566166) |
| Geoduck-juvenile-OA-exposure-RNA-EPI-116-8_S61_L008_001      | [15517237](https://www.ncbi.nlm.nih.gov/biosample/15517237) | juvenile | [PRJNA566166](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA566166) |
| Geoduck-ctenidia-RNA-1_S3_L001_001                           | [15524251](https://www.ncbi.nlm.nih.gov/biosample/15524251) | ctenidia | [PRJNA646071](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA646071) |
| Geoduck-ctenidia-RNA-2_S11_L002_001                          | [15524251](https://www.ncbi.nlm.nih.gov/biosample/15524251) | ctenidia | [PRJNA646071](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA646071) |
| Geoduck-ctenidia-RNA-3_S19_L003_001                          | [15524251](https://www.ncbi.nlm.nih.gov/biosample/15524251) | ctenidia | [PRJNA646071](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA646071) |
| Geoduck-ctenidia-RNA-4_S27_L004_001                          | [15524251](https://www.ncbi.nlm.nih.gov/biosample/15524251) | ctenidia | [PRJNA646071](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA646071) |
| Geoduck-ctenidia-RNA-5_S35_L005_001                          | [15524251](https://www.ncbi.nlm.nih.gov/biosample/15524251) | ctenidia | [PRJNA646071](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA646071) |
| Geoduck-ctenidia-RNA-6_S43_L006_001                          | [15524251](https://www.ncbi.nlm.nih.gov/biosample/15524251) | ctenidia | [PRJNA646071](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA646071) |
| Geoduck-ctenidia-RNA-7_S51_L007_001                          | [15524251](https://www.ncbi.nlm.nih.gov/biosample/15524251) | ctenidia | [PRJNA646071](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA646071) |
| Geoduck-ctenidia-RNA-8_S59_L008_001                          | [15524251](https://www.ncbi.nlm.nih.gov/biosample/15524251) | ctenidia | [PRJNA646071](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA646071) |
| Geoduck-gonad-RNA-1_S1_L001_001                              | [15524260](https://www.ncbi.nlm.nih.gov/biosample/15524260) | gonad    | [PRJNA646071](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA646071) |
| Geoduck-gonad-RNA-2_S9_L002_001                              | [15524260](https://www.ncbi.nlm.nih.gov/biosample/15524260) | gonad    | [PRJNA646071](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA646071) |
| Geoduck-gonad-RNA-3_S17_L003_001                             | [15524260](https://www.ncbi.nlm.nih.gov/biosample/15524260) | gonad    | [PRJNA646071](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA646071) |
| Geoduck-gonad-RNA-4_S25_L004_001                             | [15524260](https://www.ncbi.nlm.nih.gov/biosample/15524260) | gonad    | [PRJNA646071](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA646071) |
| Geoduck-gonad-RNA-5_S33_L005_001                             | [15524260](https://www.ncbi.nlm.nih.gov/biosample/15524260) | gonad    | [PRJNA646071](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA646071) |
| Geoduck-gonad-RNA-6_S41_L006_001                             | [15524260](https://www.ncbi.nlm.nih.gov/biosample/15524260) | gonad    | [PRJNA646071](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA646071) |
| Geoduck-gonad-RNA-7_S49_L007_001                             | [15524260](https://www.ncbi.nlm.nih.gov/biosample/15524260) | gonad    | [PRJNA646071](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA646071) |
| Geoduck-gonad-RNA-8_S57_L008_001                             | [15524260](https://www.ncbi.nlm.nih.gov/biosample/15524260) | gonad    | [PRJNA646071](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA646071) |
| Geoduck-heart-RNA-1_S2_L001_001                              | [15524261](https://www.ncbi.nlm.nih.gov/biosample/15524261) | heart    | [PRJNA646071](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA646071) |
| Geoduck-heart-RNA-2_S10_L002_001                             | [15524261](https://www.ncbi.nlm.nih.gov/biosample/15524261) | heart    | [PRJNA646071](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA646071) |
| Geoduck-heart-RNA-3_S18_L003_001                             | [15524261](https://www.ncbi.nlm.nih.gov/biosample/15524261) | heart    | [PRJNA646071](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA646071) |
| Geoduck-heart-RNA-4_S26_L004_001                             | [15524261](https://www.ncbi.nlm.nih.gov/biosample/15524261) | heart    | [PRJNA646071](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA646071) |
| Geoduck-heart-RNA-5_S34_L005_001                             | [15524261](https://www.ncbi.nlm.nih.gov/biosample/15524261) | heart    | [PRJNA646071](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA646071) |
| Geoduck-heart-RNA-6_S42_L006_001                             | [15524261](https://www.ncbi.nlm.nih.gov/biosample/15524261) | heart    | [PRJNA646071](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA646071) |
| Geoduck-heart-RNA-7_S50_L007_001                             | [15524261](https://www.ncbi.nlm.nih.gov/biosample/15524261) | heart    | [PRJNA646071](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA646071) |
| Geoduck-heart-RNA-8_S58_L008_001                             | [15524261](https://www.ncbi.nlm.nih.gov/biosample/15524261) | heart    | [PRJNA646071](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA646071) |
| NR006_S3_L001_001                                            | [15524260](https://www.ncbi.nlm.nih.gov/biosample/15524260) | gonad    | [PRJNA646071](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA646071) |
| NR006_S3_L002_001                                            | [15524260](https://www.ncbi.nlm.nih.gov/biosample/15524260) | gonad    | [PRJNA646071](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA646071) |
| NR012_S1_L001_001                                            | [15524251](https://www.ncbi.nlm.nih.gov/biosample/15524251) | ctenidia | [PRJNA646071](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA646071) |
| NR012_S1_L002_001                                            | [15524251](https://www.ncbi.nlm.nih.gov/biosample/15524251) | ctenidia | [PRJNA646071](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA646071) |
| Trueseq-stranded-mRNA-libraries-GeoRNA1-A1-NR006_S1_L001     | [15524260](https://www.ncbi.nlm.nih.gov/biosample/15524260) | gonad    | [PRJNA646071](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA646071) |
| Trueseq-stranded-mRNA-libraries-GeoRNA1-A1-NR006_S1_L002     | [15524260](https://www.ncbi.nlm.nih.gov/biosample/15524260) | gonad    | [PRJNA646071](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA646071) |
| Trueseq-stranded-mRNA-libraries-GeoRNA3-C1-NR012_S2_L001     | [15524251](https://www.ncbi.nlm.nih.gov/biosample/15524251) | ctenidia | [PRJNA646071](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA646071) |
| Trueseq-stranded-mRNA-libraries-GeoRNA3-C1-NR012_S2_L002     | [15524251](https://www.ncbi.nlm.nih.gov/biosample/15524251) | ctenidia | [PRJNA646071](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA646071) |
