---
layout: post
title: SRA Submission - Ronits C.gigas Ploidy WGBS
date: '2020-11-13 08:33'
tags:
  - SRA
  - Crassostrea gigas
  - Pacific oyster
  - ploidy
  - diploid
  - triploid
  - wgbs
  - BSseq
categories:
  - SRA Submission
---
A few days ago, [we received the whole genome bisulfite sequencing (WBGS) data (20201110)](https://robertslab.github.io/sams-notebook/2020/11/10/Data-Received-C.gigas-Ploidy-WGBS-from-Ronits-Project-via-ZymoResearch.html) from [Ronit's _C.gigas_ diploid/triploid dessication/heat stress experiment (GitHub repo)](https://github.com/RobertsLab/project-gigas_ploidy).

Now, I need to get these submitted to the [NCBI short read archive (SRA)](https://www.ncbi.nlm.nih.gov/sra).

For all publications, we should reference the SRA BioProject:

- [PRJNA678408](https://www.ncbi.nlm.nih.gov/sra/PRJNA678408)

A summary table is provided below which includes individual SRA accessions for each sample:



| Library_Name | SeqID     | Tissue   | Ploidy   | Dessication | Heat_Stress | Library_kit                             | SRA_BioProject                                              | SRA_accession                                             |
|--------------|-----------|----------|----------|-------------|-------------|-----------------------------------------|-------------------------------------------------------------|-----------------------------------------------------------|
| D11-C        | zr3534_1  | ctenidia | diploid  | yes         | no          | Zymo-Seq WGBS Library Kit (Cat#: D5465) | [PRJNA678408](https://www.ncbi.nlm.nih.gov/sra/PRJNA678408) | [SRX9508698](https://www.ncbi.nlm.nih.gov/sra/SRX9508698) |
| D12-C        | zr3534_2  | ctenidia | diploid  | yes         | no          | Zymo-Seq WGBS Library Kit (Cat#: D5465) | [PRJNA678408](https://www.ncbi.nlm.nih.gov/sra/PRJNA678408) | [SRX9508699](https://www.ncbi.nlm.nih.gov/sra/SRX9508699) |
| D13-C        | zr3534_3  | ctenidia | diploid  | yes         | no          | Zymo-Seq WGBS Library Kit (Cat#: D5465) | [PRJNA678408](https://www.ncbi.nlm.nih.gov/sra/PRJNA678408) | [SRX9508700](https://www.ncbi.nlm.nih.gov/sra/SRX9508700) |
| D19-C        | zr3534_4  | ctenidia | diploid  | yes         | yes         | Zymo-Seq WGBS Library Kit (Cat#: D5465) | [PRJNA678408](https://www.ncbi.nlm.nih.gov/sra/PRJNA678408) | [SRX9508701](https://www.ncbi.nlm.nih.gov/sra/SRX9508701) |
| D20-C        | zr3534_5  | ctenidia | diploid  | yes         | yes         | Zymo-Seq WGBS Library Kit (Cat#: D5465) | [PRJNA678408](https://www.ncbi.nlm.nih.gov/sra/PRJNA678408) | [SRX9508702](https://www.ncbi.nlm.nih.gov/sra/SRX9508702) |
| T11-C        | zr3534_6  | ctenidia | triploid | yes         | no          | Zymo-Seq WGBS Library Kit (Cat#: D5465) | [PRJNA678408](https://www.ncbi.nlm.nih.gov/sra/PRJNA678408) | [SRX9508703](https://www.ncbi.nlm.nih.gov/sra/SRX9508703) |
| T12-C        | zr3534_7  | ctenidia | triploid | yes         | no          | Zymo-Seq WGBS Library Kit (Cat#: D5465) | [PRJNA678408](https://www.ncbi.nlm.nih.gov/sra/PRJNA678408) | [SRX9508704](https://www.ncbi.nlm.nih.gov/sra/SRX9508704) |
| T13-C        | zr3534_8  | ctenidia | triploid | yes         | no          | Zymo-Seq WGBS Library Kit (Cat#: D5465) | [PRJNA678408](https://www.ncbi.nlm.nih.gov/sra/PRJNA678408) | [SRX9508705](https://www.ncbi.nlm.nih.gov/sra/SRX9508705) |
| T19-C        | zr3534_9  | ctenidia | triploid | yes         | yes         | Zymo-Seq WGBS Library Kit (Cat#: D5465) | [PRJNA678408](https://www.ncbi.nlm.nih.gov/sra/PRJNA678408) | [SRX9508706](https://www.ncbi.nlm.nih.gov/sra/SRX9508706) |
| T20-C        | zr3534_10 | ctenidia | triploid | yes         | yes         | Zymo-Seq WGBS Library Kit (Cat#: D5465) | [PRJNA678408](https://www.ncbi.nlm.nih.gov/sra/PRJNA678408) | [SRX9508707](https://www.ncbi.nlm.nih.gov/sra/SRX9508707) |
