<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2019-10-03">

<title>robertslab.info - Data Received - C.bairdi RNAseq Day9-12-26 Infected-Uninfected</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../..//images/favicon.ico" rel="icon">
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">robertslab.info</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-bi-hdd-network" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
      <i class="bi bi-hdd-network" role="img">
</i> 
 <span class="menu-text"></span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-bi-hdd-network">    
        <li>
    <a class="dropdown-item" href="http://raven.fish.washington.edu:8787" rel="" target="_blank">
 <span class="dropdown-text">raven</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://gannet.fish.washington.edu" rel="" target="">
 <span class="dropdown-text">gannet</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-bi-journal-code" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
      <i class="bi bi-journal-code" role="img">
</i> 
 <span class="menu-text"></span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-bi-journal-code">    
        <li>
    <a class="dropdown-item" href="https://robertslab.github.io/sams-notebook/" rel="" target="">
 <span class="dropdown-text">sam</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://sr320.github.io" rel="" target="">
 <span class="dropdown-text">steven</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-bi-github" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
      <i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-bi-github">    
        <li>
    <a class="dropdown-item" href="https://github.com/RobertsLab" rel="" target="">
 <span class="dropdown-text">Lab Organization</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://github.com/RobertsLab/lab-website" rel="" target="">
 <span class="dropdown-text">Edit Roberts Lab website</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item compact">
    <a class="nav-link" href="https://calendar.google.com/calendar/embed?src=mrc305@gmail.com&amp;ctz=America/Vancouver" rel="" target=""><i class="bi bi-calendar-week" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Data Received - C.bairdi RNAseq Day9-12-26 Infected-Uninfected</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">2019</div>
                <div class="quarto-category">Tanner Crab RNAseq</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">October 3, 2019</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<section id="update-20191024-this-post-details-receipt-of-incomplete-data.-additional-sequencing-was-performed-and-that-additional-data-was-received-20191024.-this-notebook-entry-on-20191024-contains-details-on-fastq-concatenation-of-the-data-below-and-the-data-received-on-20191024." class="level4">
<h4 class="anchored" data-anchor-id="update-20191024-this-post-details-receipt-of-incomplete-data.-additional-sequencing-was-performed-and-that-additional-data-was-received-20191024.-this-notebook-entry-on-20191024-contains-details-on-fastq-concatenation-of-the-data-below-and-the-data-received-on-20191024.">UPDATE (20191024): This post details receipt of incomplete data. Additional sequencing was performed and that additional data was received 20191024. This <a href="https://robertslab.github.io/sams-notebook/posts/2019/2019-10-24-Data-Received-C.bairdi-RNAseq-Day9-12-26-Infected-Uninfected.html">notebook entry on 20191024</a> contains details on FastQ concatenation of the data below and the data received on 20191024./</h4>
<p>Finally received the RNAseq data back from NWGC that we submitted on <a href="https://robertslab.github.io/sams-notebook/posts/2019/2019-05-21-Sample-Submission-Tanner-Crab-Infected-vs-Uninfected-RNAseq.html">20190521</a>!/</p>
<p>Here’s a table with the library names and the FastQ naming schemes.</p>
<table class="table">
<thead>
<tr class="header">
<th>NWGC Sample ID</th>
<th>Investigator Sample ID</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>329772</td>
<td>D9_infected</td>
</tr>
<tr class="even">
<td>329773</td>
<td>D9_uninfected</td>
</tr>
<tr class="odd">
<td>329774</td>
<td>D12_infected</td>
</tr>
<tr class="even">
<td>329775</td>
<td>D12_uninfected</td>
</tr>
<tr class="odd">
<td>329776</td>
<td>D26_infected</td>
</tr>
<tr class="even">
<td>329777</td>
<td>D26_uninfected</td>
</tr>
</tbody>
</table>
<hr>
<p>Here’s the list of FastQ files:</p>
<ul>
<li><p>329774_S1_L001_R1_001.fastq.gz</p></li>
<li><p>329774_S1_L001_R2_001.fastq.gz</p></li>
<li><p>329774_S1_L002_R1_001.fastq.gz</p></li>
<li><p>329774_S1_L002_R2_001.fastq.gz</p></li>
<li><p>329775_S2_L001_R1_001.fastq.gz</p></li>
<li><p>329775_S2_L001_R2_001.fastq.gz</p></li>
<li><p>329775_S2_L002_R1_001.fastq.gz</p></li>
<li><p>329775_S2_L002_R2_001.fastq.gz</p></li>
<li><p>329776_S3_L001_R1_001.fastq.gz</p></li>
<li><p>329776_S3_L001_R2_001.fastq.gz</p></li>
<li><p>329776_S3_L002_R1_001.fastq.gz</p></li>
<li><p>329776_S3_L002_R2_001.fastq.gz</p></li>
<li><p>329777_S4_L001_R1_001.fastq.gz</p></li>
<li><p>329777_S4_L001_R2_001.fastq.gz</p></li>
<li><p>329777_S4_L002_R1_001.fastq.gz</p></li>
<li><p>329777_S4_L002_R2_001.fastq.gz</p></li>
</ul>
<p>All files have been added to nightingales/C_bairdi:</p>
<ul>
<li><a href="https://owl.fish.washington.edu/nightingales/C_bairdi/">nightingales/C_bairdi</a></li>
</ul>
<p>Will update readme and <a href="http://b.link/nightingales">Nightingales Google sheet</a></p>
<hr>
<p>I just realized that the list of FastQ files does not match the list of NWGC Sample IDs (329772 and 329773 do not have corresponding FastQ files). I’ve emailed the facility and this was their response:</p>
<blockquote class="blockquote">
<p>Machiko Threlkeld 6:14 PM (3 hours ago) to Sam, Peter, Stephanie</p>
<p>Hi Sam,</p>
<p>I am sorry. I should have been more clear. 2 samples of yours failed sequencing steps and we didn’t have any more samples left to repeat the process. The QC results show that those two had less than 10ul to start with.</p>
<p>Here is the summary of your project:</p>
<p># total samples submitted = 6</p>
<p># samples approved for sequencing = 6</p>
<p># samples passed sequencing QC and released = 4</p>
<p>I hope you understand.</p>
<p>Thank you, Machiko</p>
</blockquote>
<p>So, this is the first I’m hearing of any concern with these two particular samples. Especially since they passed the initial QC on <a href="https://robertslab.github.io/sams-notebook/posts/2019/2019-05-21-Sample-Submission-Tanner-Crab-Infected-vs-Uninfected-RNAseq.html">20190610</a>!/</p>
<p>Here’s my response; I’ll update this post when they respond:</p>
<blockquote class="blockquote">
<p>Sam White <a href="mailto:samwhite@uw.edu" class="email">samwhite@uw.edu</a> 8:58 PM (32 minutes ago) to Machiko, Peter, Stephanie</p>
<p>Hi Machiko,</p>
<p>I definitely do not understand.</p>
<p>The initial QC report you sent to me indicated that these two samples PASSED QC (there was only one sample that failed QC - that sample ended up getting sequenced without issue).</p>
<p>Additionally, I’m not sure why the volume of the samples is relevant. The QC report clearly indicated that both samples had less than 10uL, yet they PASSED QC. Also, if there was a concern with low sample volume, why not add the additional water to each sample? If the volumes had been adjusted to 10uL, the resulting concentrations for both of those samples would have been ~100ng/uL; on par with the other samples. So, I am having difficulty believing that the sample volume was an issue of any sort.</p>
<p>Regardless, the QC report indicated those two samples passed QC. So now what?</p>
<p>Thanks for any insight you can provide.</p>
<p>Sam</p>
</blockquote>
<hr>
<blockquote class="blockquote">
<p>Stephanie A Krauter Tue, Oct 8, 9:29 PM to Sam, Machiko, Peter</p>
<p>Hi Sam,</p>
<p>Hopefully I can clarify. If not, I’m happy to set up a phone call.</p>
<p>Samples pass initial sample QC if they have enough mass and the quality is good. Six samples passed this QC step and entered the sequencing pipeline. Once samples move into library preparation a certain volume is needed for the prep. This is the volume aspect Machiko was speaking about. The two samples that failed sequencing QC did have enough sample for one prep but not multiple. Library prep is only repeated if there is an instrument error or kit issue. This was not the case for the two samples that unfortunately failed library prep as the control looked good as did all the other samples in that batch. The volume of the samples does not have an affect on the success of a library prep. Machiko brings up the volume aspect just to note that if you wanted to attempt to sequence these samples again you would need to resubmit samples as all the sample you provided was used in library preparation.</p>
<p>Hope this helps. If you have any other questions, I am happy to help.</p>
</blockquote>
<blockquote class="blockquote">
<p>Best, Stephanie</p>
</blockquote>
<hr>
<blockquote class="blockquote">
<p>Sam White <a href="mailto:samwhite@uw.edu" class="email">samwhite@uw.edu</a> Tue, Oct 8, 9:54 PM to Stephanie, Machiko, Peter</p>
<p>Thanks for the clarification, Stephanie.</p>
<p>So, those two samples were not sequenced due to an instrument error and/or kit error? Did we just get lucky that the other four samples in this project did not get affected by the same instrument/kit error?</p>
<p>I’m also still confused on why the sample volumes wouldn’t have been adjusted to the minimum of 10uL, particularly if they had sufficient RNA…</p>
<p>Regardless, I guess these samples are toast.</p>
<p>May we please get refunded for the costs associated with those two samples ($299sample; total = $598)?</p>
<p>I’ve also noticed that we received ~20 - 33%% less data for each sample than we were expecting, based on the project quote. We were expecting ~50M reads per sample, but have received 40M reads or less per sample (sample 329777 is an exception with ~48M reads).</p>
<p>What are your thoughts on this data output, relative to what was promised?</p>
<p>Thanks for all of your help and time with this project.&gt;</p>
<p>Sam</p>
</blockquote>
<hr>
<blockquote class="blockquote">
<p>Stephanie A Krauter Oct 8, 2019, 10:04 PM to Sam, Machiko, Peter</p>
<p>Hi Sam,</p>
<p>As I stated in my previous email. Your samples did not fail because of an instrument error or kit failure. The library process looked good as evidence by the successful control and the success of other samples in that batch. Your samples failed due to the samples themselves.</p>
<p>Since this was not an instrument or kit failure, but rather a sample issue, you will still be charged the cost to prep these samples.</p>
<p>Again the volume of the samples was not a concern and had no bearing on the outcome of the library for these samples.</p>
<p>I will look into your concern regarding the number of reads per sample tomorrow.</p>
<p>Best, Stephanie</p>
</blockquote>
<hr>
<blockquote class="blockquote">
<p>Sam White <a href="mailto:samwhite@uw.edu" class="email">samwhite@uw.edu</a> Wed, Oct 9, 9:01 AM to Stephanie, Machiko, Peter</p>
<p>Ah, thanks Stephanie. I didn’t follow what you were saying in your initial email. Thanks for re-wording!</p>
<p>For additional clarification on what went wrong, primarily to attempt to avoid failures in future sequencing projects that we send to you, may I have more info?</p>
<p>When did the failure for these samples occur? When they were sequenced?</p>
<p>I’m still unclear as to why these two samples could not be repeated? Could you please elaborate on this?</p>
<p>Could you please send me the initial Bioanalyzer electropherograms for the samples associated with this project? I’d like to see if there’s any noticeable differences between the failed samples and the successful samples to try to screen samples in the future.</p>
<p>Also, in regards to you blaming the failure on the samples (which is certainly a possibility), then what’s the point of your initial QC? Since the samples passed your standards as acceptable samples, then I don’t see how the sample failure doesn’t fall on your facility’s shoulders. Don’t get me wrong, I fully understand your point of view in that the controls worked and all that, but your facility said the samples I submitted were acceptable for sequencing, based on the standards set by your lab. Thus, our samples met the necessary requirements for processing and sequencing. Subsequent failure should no longer be relegated back to us, the customer, since you already approved the samples.</p>
<p>Another point that I wanted to address was the turnaround time for this project. From initial sample drop off to data receipt was 4.5 months. After samples passed QC and were entered into the pipeline, it took 3.75 months to get data. This is well beyond the 10 - 12 week window that was promised. This was disappointing and frustrating. Adding to the frustration was that I received no communication from NWGC regarding the project status, why it was delayed, an updated ETA, when our data was ready, etc.</p>
<p>We have some upcoming RNAseq later this year and we’d like to continue to use NWGC and support a fellow Univ. of Washington lab. However, the turnaround time is a serious concern. Is there anything we can do in the future to ensure that our samples would be processed in the 10 - 12 week time frame? Is there an “expedited” service available?</p>
<p>Finally, I neglected to say “thanks” last night for your quick, after-hours email responses! Thanks for that! That’s going above and beyond, and is definitely not necessary.</p>
<p>And, thanks for sticking with me and helping me understand what went on with this project. I sincerely appreciate your time and help.</p>
<p>Sam</p>
</blockquote>
<hr>
<blockquote class="blockquote">
<p>Stephanie A Krauter Wed, Oct 9, 10:23 AM to Sam, Machiko, Peter</p>
<p>Absolutely, Sam! Again, I am happy to set up a phone call if that is easier to answer all of your questions.</p>
<p>In the meantime, I’d like to apologize for the delay in your project and lack of communication. The center’s turnaround time is about 10-12 weeks once samples pass QC. That being said, we do try to get samples returned as soon as possible meaning there are times that investigators receive their samples much sooner than the 10 weeks. Conversely the turnaround time may be longer if the production queue is long. However, that does not excuse the lack of communication and you absolutely should have been contacted. I will make sure to talk with my team about this today.</p>
<p>We do have a rush option which includes a fee of 10% of the total project cost.</p>
<p>Initial QC only means that samples meet the minimum requirements to enter the pipeline. It absolutely does not guarantee that a successful library can be made from the sample nor do we guarantee that. To ensure that a sample failure was not due to something we did we include a control sample. All of these samples were prepped with liquid handlers and again, the control and all other samples in this batch were successful indicating that the reason these samples failed was an issue with the sample.</p>
<p>One main reason a sample fails to successfully generate a library is sample quality. Typically any sample with a RIN less than 7 fails initial QC. However, a bioanalyzer wasn’t run since you stated “Additionally, I just wanted to pass along the heads up that these samples will not generate a Bioanalyzer RIN. The samples we’re submitting are from tanner crab and this species only generates a single rRNA band, thus, no RIN.” and therefore quality was not assessed. This may or may not have been a contributing factor in why these samples failed.</p>
<p>In regards to billing, you were quoted ~$299 per sample. That is the cost for the entire service. However, when Peter invoices he only bills for the portion of the service performed. Since the two samples were not sequenced, you will only be billed up through library prep.</p>
<p>Hope this clarifies things. I will circle back after my 10:30 meeting regarding the number of reads per sample.</p>
<p>Best, Stephanie</p>
</blockquote>
<hr>
<blockquote class="blockquote">
<p>Stephanie A Krauter Fri, Oct 11, 11:12 AM to Sam, Machiko, Peter</p>
<p>Hi Sam,</p>
<p>It appears our project manager did jump the gun a bit on releasing these. I have asked the sequencing team to top these samples off and they will be going on the sequencers today.</p>
<p>Best, Stephanie</p>
</blockquote>
<hr>
<blockquote class="blockquote">
<p>Sam White <a href="mailto:samwhite@uw.edu" class="email">samwhite@uw.edu</a> Mon, Oct 14, 7:14 AM (11 days ago) to Stephanie, Machiko, Peter</p>
<p>Thanks for the update and billing clarification. The quote didn’t break out individual costs of library prep/sequencing, so I just assumed it was a all/none per sample pricing scheme.</p>
<p>Sorry about the confusion on the Bioanalyzer. My intent was to simply give the heads up that the samples would appear “abnormal” (compared to mammalian samples); not suggest they not be run. Would’ve been useful to see if these samples appeared different than the others.</p>
<p>Anyway, thanks again for taking the time to handle my ranting and taking the time to explain what was happening here! Looking forward to the additional data.</p>
<p>Sam</p>
</blockquote>
<hr>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>